<?php
/**
 * Created by PhpStorm.
 * User: zhangyapin
 * Date: 2018/9/19
 * Time: 下午3:04
 */
class AuthorsController extends AbstractController {
    const PAGESIZE = 48;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->_active = "novel";
        $this->_view->active = $this->_active;
    }
    public function listAction(){
        try{
            $id = $this->get("id");
            $authorModel = new AuthorModel();
            $params = array(
                "status" => AuthorModel::AUTHOR_STATUS
            );
            $this->_view->novel_class_name = "小说";
            if($id > 0){
                $page = $this->get("page");
                $page = $page > 0 ? $page : 1;
                $offset = ($page-1)*self::PAGESIZE;
                $pageSize = self::PAGESIZE;
                $isCount = true;

                $params['novel_class_id'] = $id;
                $this->_view->novel_class_name = NovelModel::$_novel_class_type[$id]."小说";
                $this->_view->seo = array(
                    "title" => isset(NovelModel::$_novel_class_type[$id])?str_replace("{novelclass}",NovelModel::$_novel_class_type[$id],$this->_seo['authorlist']['title']):"",
                    "keywords" => isset(NovelModel::$_novel_class_type[$id])?str_replace("{novelclass}",NovelModel::$_novel_class_type[$id],$this->_seo['authorlist']['keywords']):"",
                    "description" => isset(NovelModel::$_novel_class_type[$id])?str_replace(array("{novelclass}"),array(NovelModel::$_novel_class_type[$id]),$this->_seo['authorlist']['description']):"",
                );
            }else{
                $offset = 0;
                $pageSize = 0;
                $isCount = false;
                $this->_view->seo = array(
                    "title" => $this->_seo['allauthorlist']['title'],
                    "keywords" => $this->_seo['allauthorlist']['keywords'],
                    "description" => $this->_seo['allauthorlist']['description']
                );
            }


            $authorList = $authorModel->getList($params,$offset,$pageSize,$isCount);
            $this->_view->author_list = $authorList['list'];
            $authors = "";
            foreach ($authorList['list'] as $value){
                $authors .= $value['author_name'];
            }

            if($id > 0){
                $this->_view->page_num = ceil($authorList['cnt']/self::PAGESIZE);
                $this->_view->page_url = $this->_webUrl."/xiaoshuo/".NovelModel::$_novel_class_pinxie[$id]."_".$id.".html";
                $this->_view->cur_page = $page;
            }


        }catch (Exception $e){
            $this->processException($this->getRequest()->getControllerName(),$this->getRequest()->getActionName(),$e);
        }

    }
}