<?php $this->display('section/header.phtml');?>

<h1 class="star am-container mcenter"><span><img src="/images/star.png" alt="小说文学">小说文学</span></h1>
<div id="cattlist" class="am-container">
    <ul class="am-avg-sm-1 am-avg-md-3 am-avg-lg-4">
        <?php foreach ($this->author_list as $value){?>
        <li>
            <div class="cattlist_0">
                <div class="cattlist_1">
                    <div class="am-g">
                        <div class="am-u-sm-4 am-u-md-5 am-u-lg-5 am-vertical-align">
                            <div class="am-vertical-align-middle">
                                <img src="<?=\YC\Common::getUrl($value['pic'])?>" alt="<?=$value['author_name']?>">
                            </div>
                        </div>
                        <div class="am-u-sm-8 am-u-md-7 am-u-lg-7">
                            <h2><?=$value['author_name']?></h2>
                        </div>
                    </div>
                </div>
                <div class="cattlist_2">
                    <p><?=$value['description']?></p>
                </div>
                <div class="cattlist_3">
                    <a class="am-btn am-btn-warning" title="进入作者专栏" href="<?=$this->web_url?>/xiaoshuo/author_<?=$value['id']?>_1.html">进入专栏</a>
                </div>
            </div>
        </li>
    <?php }?>
    </ul>
</div>

<?php $this->display('section/footer.phtml');?>