<?php $this->display('section/header.phtml'); ?>

    <div class="am-g am-container">
        <div class="am-u-sm-12 am-u-md-12 am-u-lg-8">
            <ol class="am-breadcrumb breadcrumb">
                <li><a href="<?= $this->web_url ?>" title="文学星空" class="am-icon-home">首页</a></li>
                <li>
                    <?php if($this->article_type['parent_id'] == 0){?>
                        <a href="<?= $this->web_url ?>/<?=$this->url_type?>/<?=$this->chapter_url_type?>_<?= $this->article_info['author_id'] ?>_1.html" title="<?= $this->article_info['author'] ?>">
                            <strong class="fn"><?= $this->article_info['author'] ?></strong>
                        </a>
                    <?php }else{?>
                        <a href="<?= $this->web_url ?>/<?=$this->url_type?>/chapter_<?= $this->article_type['id'] ?>_1.html" title="<?= $this->article_type['name'] ?>">
                            <strong class="fn"><?= $this->article_type['name'] ?></strong>
                        </a>
                    <?php }?>

                </li>
                <li>
                    <a href="<?= $this->web_url ?>/<?=$this->url_type?>/detail_<?= $this->article_info['id'] ?>.html" title="<?= $this->article_info['name'] ?>"><strong class="fn">#<?= $this->article_info['name'] ?>#</strong></a>
                </li>
            </ol>
            <div>
                <h1><?= $this->article_info['name'] ?></h1>
            </div>
            <div>作者：<strong><?= $this->article_info['author'] ?></strong></div>
            <div class="contents">
                <div class="gushi">
                    <?php
                    $content = $this->article_info['content'];
                    $search = array(
                        '<font color="#800080" face="黑体">[注解]</font>',
                        '<font color="#800080" face="黑体">[韵译]</font>',
                        '<font color="#800080" face="黑体">[评析]</font>'
                    );
                    $replace = array(
                        '<strong style="color: #e1652f">[注解]</strong>',
                        '<strong style="color: #e1652f">[韵译]</strong>',
                        '<strong style="color: #e1652f">[评析]</strong>'
                    );
                    $content = str_replace($search, $replace, $content);
                    echo $content;
                    ?>
                </div>
                <?php if (isset($this->article_info['description']) && $this->article_info['description']) { ?>
                    <div class="gushi">
                        <div data-am-widget="titlebar" class="am-titlebar am-titlebar-default gushi-title">
                            <h2 class="am-titlebar-title">
                                <span><?= $this->article_info['name'] ?>简介</span>
                            </h2>
                        </div>
                        <div>
                            <?= $this->article_info['description'] ?>
                        </div>
                    </div>
                <?php } ?>
                <?php if ($this->article_info['translate']) { ?>
                    <div class="gushi">
                        <div data-am-widget="titlebar" class="am-titlebar am-titlebar-default gushi-title">
                            <h2 class="am-titlebar-title"><?= $this->article_info['name'] ?>翻译</h2>
                        </div>
                        <div>
                            <?= $this->article_info['translate'] ?>
                        </div>
                    </div>
                <?php } ?>
                <?php if ($this->article_info['notes']) { ?>
                    <div class="gushi">
                        <div data-am-widget="titlebar" class="am-titlebar am-titlebar-default gushi-title">
                            <h2 class="am-titlebar-title"><?= $this->article_info['name'] ?>注释</h2>
                        </div>
                        <div>
                            <?= $this->article_info['notes'] ?>
                        </div>
                    </div>
                <?php } ?>
                <?php if ($this->article_info['shangxi']) { ?>
                    <div class="gushi">
                        <div data-am-widget="titlebar" class="am-titlebar am-titlebar-default gushi-title">
                            <h2 class="am-titlebar-title"><?= $this->article_info['name'] ?>赏析</h2>
                        </div>
                        <div>
                            <?= $this->article_info['shangxi'] ?>
                        </div>
                    </div>
                <?php } ?>
            </div>

            <ul data-am-widget="pagination" class="am-pagination am-pagination-default">
                <?php if ($this->chapter['pre']) { ?>
                    <li class="am-pagination-prev ">
                        <a href="<?= $this->web_url ?>/<?=$this->url_type?>/detail_<?= $this->chapter['pre'] ?>.html" class="">上一章</a>
                    </li>
                <?php } ?>
                <li class="">
                    <?php if ($this->article_type['parent_id'] == 0) { ?>
                        <a href="<?= $this->web_url ?>/<?=$this->url_type?>/<?=$this->chapter_url_type?>_<?= $this->article_info['author_id'] ?>_1.html" class="">回目录</a>
                    <?php }else{?>
                        <a href="<?= $this->web_url ?>/<?=$this->url_type?>/chapter_<?= $this->article_info['class_type'] ?>_1.html" class="">回目录</a>
                    <?php }?>
                </li>
                <?php if ($this->chapter['next']) { ?>
                    <li class="am-pagination-next ">
                        <a href="<?= $this->web_url ?>/<?=$this->url_type?>/detail_<?= $this->chapter['next'] ?>.html" class="">下一章</a>
                    </li>
                <?php } ?>
            </ul>
        </div>
        <div class="am-u-sm-0 am-u-md-0 am-u-lg-4">

            <div data-am-widget="titlebar" class="am-titlebar am-titlebar-default">
                <h2 class="am-titlebar-title ">
                    相关作品
                </h2>
                <nav class="am-titlebar-nav">
                    <?php if ($this->article_type['parent_id'] == 0) { ?>
                        <a href="<?= $this->web_url ?>/<?=$this->url_type?>/<?=$this->chapter_url_type?>_<?= $this->article_info['author_id'] ?>_1.html">more &raquo;</a>
                    <?php } else { ?>
                        <a href="<?= $this->web_url ?>/<?=$this->url_type?>/chapter_<?= $this->article_type['id'] ?>_1.html">more &raquo;</a>
                    <?php } ?>
                </nav>
            </div>

            <div data-am-widget="list_news" class="am-list-news am-list-news-default right-bg">
                <ul class="am-list">
                    <?php foreach ($this->relate_article as $value) {
                        if ($value['id'] == $this->article_info['id']) continue;
                        ?>
                        <li class="am-g am-list-item-desced am-list-item-thumbed am-list-item-thumb-left">

                            <div class=" am-u-sm-8 am-list-main">
                                <h3 class="am-list-item-hd">
                                    <a href="<?= $this->web_url ?>/<?=$this->url_type?>/detail_<?= $value['id'] ?>.html" title="<?= empty($value['author']) ?"" : $value['author']."/"?><?= $value['name'] ?>"><?= empty($value['author']) ?"" : $value['author']."/"?><?= $value['name'] ?></a>
                                </h3>

<!--                                <div class="am-list-item-text">--><!--</div>-->
                            </div>
                        </li>
                        <hr data-am-widget="divider" style="" class="am-divider am-divider-default"/>
                    <?php } ?>

                </ul>
            </div>

        </div>
    </div>
<?php $this->display('section/footer.phtml'); ?>