<div data-am-widget="gotop" class="am-gotop am-gotop-fixed" >
    <a href="#top" title="回到顶部">
        <span class="am-gotop-title">回到顶部</span>
        <i class="am-gotop-icon am-icon-chevron-up"></i>
    </a>
</div>
<footer>
    <div class="content">
        <ul class="am-avg-sm-5 am-avg-md-5 am-avg-lg-5 am-thumbnails">
            <li><a href="#">关于我们</a></li>
            <li><a href="#">阅读指南</a></li>
            <li><a href="#">免责声明</a></li>
            <li><a href="#">广告合作</a></li>
            <li><a href="#">友情链接</a></li>
        </ul>
        <div class="btnlogo"><a href="<?=$this->web_url?>" title="文学星空"><img src="/images/logo_footer.png" alt="文学星空"/></a></div>
        <p><a href="<?=$this->web_url?>/" title="文学星空">文学星空</a> eeeaaa.cn © 京ICP备17057981号-1<br> >>本站作品均从网络收集，如有不妥，敬请联系本站以便及时撤除<<</p>
    </div>
</footer>
<script>
    var href = location.href;
    if( href.search("tangshi") > 0){
        $("#tangshi").addClass("am-nav-active");
    }else if(href.search("xiaoshuo") >0){
        $("#novel").removeClass("am-dropdown");
        $("#novel").addClass("am-nav-active");
        $("#novel").addClass("am-dropdown");
    }else if(href.search("ciqu") > 0){
        $("#songyuan").addClass("am-nav-active");
    }else{
        $("#index").addClass("am-nav-active");
    }

</script>
</body>
</html>