<div data-am-widget="gotop" class="am-gotop am-gotop-fixed" >
    <a href="#top" title="回到顶部">
        <span class="am-gotop-title">回到顶部</span>
        <i class="am-gotop-icon am-icon-chevron-up"></i>
    </a>
</div>

<footer>
    <div class="content">
        <p><strong>扫描二维码关注微信公众号『星阅』，每天陪你，阅读<a href="https://www.eeeaaa.cn" title="文学">文学</a>星空下。</strong></p>
        <div class="btnlogo"><img src="/images/qrcode_258.jpg" width="172" height="172"/> <img src="/images/logo_footer.png" width="300" alt="文学星空"/></div>
        <p><a href="https://www.eeeaaa.cn" title="文学星空">文学星空</a> <a href="https://www.eeeaaa.cn" title="文学星空">www.eeeaaa.cn</a> © 京ICP备17057981号-1</p>
    </div>
</footer>
<script>
    var href = location.href;

    if( href.search("tangshi") > 0 || href.search("ciqu") > 0 || href.search("wenyanwen") > 0){
        $("#tangshi").removeClass("am-dropdown");
        $("#tangshi").addClass("am-nav-active");
        $("#tangshi").addClass("am-dropdown");
    }else if(href.search("gudian") >0){
        $("#gudian").removeClass("am-dropdown");
        $("#gudian").addClass("am-nav-active");
        $("#gudian").addClass("am-dropdown");
    }else if(href.search("xiaoshuo") >0){
        var cls = "<?=$this->novel['novel_class_id']?:''?>";
        if(cls == "7"){
            $("#gudian").removeClass("am-dropdown");
            $("#gudian").addClass("am-nav-active");
            $("#gudian").addClass("am-dropdown");
        }else{
            $("#novel").removeClass("am-dropdown");
            $("#novel").addClass("am-nav-active");
            $("#novel").addClass("am-dropdown");
        }

    }else{
        $("#index").addClass("am-nav-active");
    }

</script>
</body>
</html>