<footer>
    <div class="content">
        <ul class="am-avg-sm-5 am-avg-md-5 am-avg-lg-5 am-thumbnails">
            <li><a href="#">关于我们</a></li>
            <li><a href="#">阅读指南</a></li>
            <li><a href="#">免责声明</a></li>
            <li><a href="#">广告合作</a></li>
            <li><a href="#">友情链接</a></li>
        </ul>
        <div class="btnlogo"><a href="http://eeeaaa.cn/" title="文学星空"><img src="images/logo_footer.png" alt="文学星空"/></a></div>
        <p><a href="http://eeeaaa.cn/" title="文学星空">文学星空</a> eeeaaa.cn © 京ICP备17057981号-1<br> >>本站作品均从网络收集，如有不妥，敬请联系本站以便及时撤除<<</p>
    </div>
</footer>
</body>
</html>