<!doctype html>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>文学星空</title>

    <!--360 browser -->
    <meta name="renderer" content="webkit">
    <meta name="author" content="wos">
    <!-- Android -->
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="/images/i/app.png">
    <!--Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Amaze UI"/>
    <link rel="apple-touch-icon-precomposed" href="/images/i/app.png">
    <!--Win8 or 10 -->
    <meta name="msapplication-TileImage" content="/images/i/app.png">
    <meta name="msapplication-TileColor" content="#e1652f">

    <link rel="icon" href="/images/i/favicon.ico">
    <link rel="stylesheet" href="/assets/css/amazeui.css">
    <link rel="stylesheet" href="/css/public.css">

    <!--[if (gte IE 9)|!(IE)]><!-->
    <script src="/assets/js/jquery.min.js"></script>
    <!--<![endif]-->
    <!--[if lte IE 8 ]>
    <script src="http://libs.baidu.com/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
    <script src="/assets/js/amazeui.ie8polyfill.min.js"></script>
    <![endif]-->
    <script src="/assets/js/amazeui.min.js"></script>
    <script src="/js/public.js"></script>
</head>
<body>
<header class="am-topbar am-topbar-fixed-top wos-header">
    <div class="am-container">
        <div class="am-topbar-brand">
            <a href="<?=$this->web_url?>" title="文学星空"><img src="/images/logo_red.png" alt="文学星空"></a>
        </div>

        <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-warning am-show-sm-only"
                data-am-collapse="{target: '#collapse-head'}">
            <span class="am-sr-only">导航切换</span>
            <span class="am-icon-bars"></span>
        </button>

        <div class="am-collapse am-topbar-collapse" id="collapse-head">
            <ul class="am-nav am-nav-pills am-topbar-nav">
                <li class="am-nav-active"><a href="<?=$this->web_url?>" title="文学星空">首页</a></li>
                <li class="am-dropdown" data-am-dropdown>
                    <a class="am-dropdown-toggle" title="小说" data-am-dropdown-toggle href="javascript:;">
                        小说 <span class="am-icon-caret-down"></span>
                    </a>
                    <ul class="am-dropdown-content">
                        <li class="am-dropdown-header">分类</li>
                        <?php foreach ($this->novel_class as $key=>$value){
                                if($key == NovelModel::NOVEL_CLASS_XIANDAI)continue;
                            ?>
                        <li><a href="#" title="<?=$value?>小说"><?=$value?>小说</a></li>
                        <?php } ?>
                    </ul>
                </li>
                <li><a href="#" title="先秦文学">先秦</a></li>
                <li><a href="#" title="两汉文学">两汉</a></li>
                <li><a href="#" title="魏晋文学">魏晋</a></li>
                <li><a href="#" title="隋唐文学">隋唐</a></li>
                <li><a href="#" title="宋元文学">宋元</a></li>
                <li><a href="#" title="明清文学">明清</a></li>
                <li><a href="#" title="近代文学">近代</a></li>
                <li><a href="#" title="现代文学">现代</a></li>
                <li><a href="#" title="外国文学">外国</a></li>
            </ul>
        </div>
    </div>
</header>