<!doctype html>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <title><?=!empty($this->seo['title'])?$this->seo['title']:"小说|诗歌|散文|文学网 - 做你最喜爱的小说在线阅读,文学网"?></title>
    <meta name="keywords" content="<?=!empty($this->seo['keywords'])?$this->seo['keywords']:"文学星空,文学网,小说,小说网,武侠小说,言情小说,校园小说,玄幻小说,恐怖小说,先秦文学,两汉文学,魏晋文学,隋唐文学,宋元文学,明清文学,近代文学,现代文学,外国文学,唐诗,宋词,元曲,诗歌,散文"?>" />
    <meta name="description" content="<?=!empty($this->seo['description'])?$this->seo['description']:"文学星空 - 中国最优质的小说，美文，文学网。做你最喜爱的在线阅读小说网，文学网。提供最人性化的阅读体验，诗歌小说散文，名人名言大全的文学网。让人们在宣泄的都市中体验阅读的乐趣，享受文学的熏陶。找诗歌散文小说美文在线阅读，上文学星空小说文学网。"?>" />
    <meta name="author" content="www.eeeaaa.cn">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Android -->
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="/images/i/app.png">
    <!--Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Amaze UI"/>
    <link rel="apple-touch-icon-precomposed" href="/images/i/app.png">
    <!--Win8 or 10 -->
    <meta name="msapplication-TileImage" content="/images/i/app.png">
    <meta name="msapplication-TileColor" content="#e1652f">

    <link rel="icon" href="/images/i/favicon.ico">
    <link rel="stylesheet" href="/assets/css/amazeui.css">
    <link rel="stylesheet" href="/css/public.css">

    <!--[if (gte IE 9)|!(IE)]><!-->
    <script src="/assets/js/jquery.min.js"></script>
    <!--<![endif]-->
    <!--[if lte IE 8 ]>
    <script src="/js/jquery.min.js"></script>
    <script src="/js/modernizr.js"></script>
    <script src="/assets/js/amazeui.ie8polyfill.min.js"></script>
    <![endif]-->
    <script src="/assets/js/amazeui.min.js"></script>
    <script src="/js/public.js"></script>
    <script>
        var _hmt = _hmt || [];
        (function() {
            var hm = document.createElement("script");
            hm.src = "https://hm.baidu.com/hm.js?c7c48f436d9a5682c75a4b59bc508e33";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        })();
    </script>
    <style>
        #novel > a:after {
            display: block;
        }
    </style>
</head>
<body>
<header class="am-topbar am-topbar-fixed-top wos-header">
    <div class="am-container">
        <?php if($this->active == "index"){?>
            <h1 class="am-topbar-brand">
                <a href="<?=$this->web_url?>" title="文学星空"><img src="/images/logo_red.png" alt="文学星空"></a>
            </h1>
        <?php }else{ ?>
        <div class="am-topbar-brand">
            <a href="<?=$this->web_url?>" title="文学星空"><img src="/images/logo_red.png" alt="文学星空"></a>
        </div>
        <?php }?>
        <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-warning am-show-sm-only"
                data-am-collapse="{target: '#collapse-head'}">
            <span class="am-sr-only">导航切换</span>
            <span class="am-icon-bars"></span>
        </button>

        <div class="am-collapse am-topbar-collapse" id="collapse-head">
            <ul class="am-nav am-nav-pills am-topbar-nav">
                <li id="index"><a href="<?=$this->web_url?>" title="文学星空">首页</a></li>
                <li id="novel" class="am-dropdown"  data-am-dropdown >
                    <a class="am-dropdown-toggle" title="小说" data-am-dropdown-toggle href="javascript:;" style="display:block">
                        小说 <span class="am-icon-caret-down"></span>
                    </a>
                    <ul class="am-dropdown-content">
                        <li class="am-dropdown-header"><a href="<?=$this->web_url?>/xiaoshuo/author.html" title="小说作者" style="padding: 0;color: #e1652f"><strong>小说作者列表</strong></a ></li>
                        <?php foreach ($this->novel_class as $key=>$value){
                            ?>
                        <li><a href="<?=$this->web_url?>/xiaoshuo/<?=$this->pinxie[$key]?>_<?=$key?>.html" title="<?=$value?>小说"><?=$value?>小说</a></li>
                        <?php } ?>
                    </ul>
                </li>
<!--                <li id="xianqin"><a href="#" title="先秦文学">先秦</a></li>-->
<!--                <li id="lianghan"><a href="#" title="两汉文学">两汉</a></li>-->
<!--                <li id="weijin"><a href="#" title="魏晋文学">魏晋</a></li>-->
                <li id="tangshi" ><a href="<?=$this->web_url?>/tangshi/list_<?=ArticlesTypeModel::ARTICLE_TYPE_TANG?>.html" title="隋唐文学">隋唐</a></li>
                <li id="songyuan"><a href="<?=$this->web_url?>/ciqu/list_<?=ArticlesTypeModel::ARTICLE_TYPE_SONG?>.html" title="宋元文学">宋元</a></li>
<!--                <li id="mingqing"><a href="#" title="明清文学">明清</a></li>-->
<!--                <li id="jindai"><a href="#" title="近代文学">近代</a></li>-->
<!--                <li id="xiandai"><a href="#" title="现代文学">现代</a></li>-->
<!--                <li id="waiguo"><a href="#" title="外国文学">外国</a></li>-->
            </ul>
        </div>
    </div>
</header>