<?php $this->display('section/header.phtml');?>
    <!--新版首页-->
    <!--首屏1-->
    <div class="banner">
        <div class="am-g am-container">
            <div class="am-u-sm-12 am-u-md-12 am-u-lg-8">
                <div data-am-widget="slider" class="am-slider am-slider-c1" data-am-slider='{"directionNav":false}'  data-am-flexslider="{playAfterPaused: 2000}">
                    <ul class="am-slides">
                        <li>
                            <a href="https://www.eeeaaa.cn/gudian/chapter_1507_1.html" title="红楼梦 曹雪芹 文学星空">
                                <img src="/images/index/hlm1.jpg" alt="红楼梦 曹雪芹 文学星空"></a>
                            <div class="am-slider-desc">红楼梦 - 曹雪芹</div>
                        </li>
                        <li>
                            <a href="https://www.eeeaaa.cn/gudian/chapter_1506_1.html" title="西游记 吴承恩 文学星空">
                                <img src="/images/index/xyj2.jpg" alt="西游记 吴承恩 文学星空">
                            </a >
                            <div class="am-slider-desc">西游记 - 吴承恩</div>
                        </li>
                        <li>
                            <a href="https://www.eeeaaa.cn/gudian/chapter_1504_1.html" title="三国演义 罗贯中 文学星空">
                                <img src="/images/index/sgyy3.jpg" alt="三国演义 罗贯中 文学星空">
                            </a>
                            <div class="am-slider-desc">三国演义 - 罗贯中</div>
                        </li>
                        <li>
                            <a href="https://www.eeeaaa.cn/gudian/chapter_1505_1.html" title="水浒传 施耐庵 文学星空">
                                <img src="/images/index/shz4.jpg" alt="水浒传 施耐庵 文学星空">
                            </a >
                            <div class="am-slider-desc">水浒传 - 施耐庵</div>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="am-u-sm-0 am-u-md-0 am-u-lg-4 padding-none">
                <h1 class="star am-container"><span><img src="images/star.png" alt="文学星空">文学星空</span></h1>
                <ul class="padding-none am-gallery am-avg-sm-2 am-avg-md-4 am-avg-lg-2 am-gallery-overlay" data-am-gallery="{ pureview: true }" >
                    <li>
                        <div class="am-gallery-item">
                            <a href="https://www.eeeaaa.cn/tangshi/gushi_1_1.html" title="李白诗集 文学星空">
                                <img src="https://www.eeeaaa.cn/group1/M00/00/02/rBH2TVvG_R6AFsSVAAAVJl0hkIU732.jpg" alt="李白诗集 文学星空" style="height: 166px"/>
                                <h3 class="am-gallery-title">李白诗集</h3>
                            </a>
                        </div>
                    </li>
                    <li>
                        <div class="am-gallery-item">
                            <a href="https://www.eeeaaa.cn/tangshi/gushi_3_1.html" title="杜甫诗集 文学星空">
                                <img src="https://www.eeeaaa.cn/group1/M00/00/02/rBH2TVvIHAmAUHocAAAVGeXF_O4822.jpg" alt="杜甫诗集 文学星空" style="height: 166px"/>
                                <h3 class="am-gallery-title">杜甫诗集</h3>
                            </a>
                        </div>
                    </li>
                    <li>
                        <div class="am-gallery-item">
                            <a href="https://www.eeeaaa.cn/tangshi/gushi_4_1.html" title="王维诗集 文学星空">
                                <img src="https://www.eeeaaa.cn/group1/M00/00/02/rBH2TVvIWA-AHRCXAAASjajkf8I327.jpg" alt="王维诗集 文学星空" style="height: 166px"/>
                                <h3 class="am-gallery-title">王维诗集</h3>
                            </a>
                        </div>
                    </li>
                    <li>
                        <div class="am-gallery-item">
                            <a href="https://www.eeeaaa.cn/tangshi/gushi_2_1.html" title="白居易诗集 文学星空">
                                <img src="https://www.eeeaaa.cn/group1/M00/00/02/rBH2TVvIFBuAECWyAAAaHuOU5Uw811.jpg" alt="白居易诗集 文学星空" style="height: 166px"/>
                                <h3 class="am-gallery-title">白居易诗集</h3>
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!--首屏2-->
    <div class="am-container">
        <ul class="padding-none banner2 am-gallery am-avg-sm-2 am-avg-md-4 am-avg-lg-4 am-gallery-overlay" data-am-gallery="{ pureview: true }" >
            <li>
                <div class="am-gallery-item">
                    <a href="https://www.eeeaaa.cn/tangshi/chapter_17_1.html" title="唐诗三百首 文学星空">
                        <img src="/images/index/ts.jpeg" alt="唐诗三百首 文学星空" style="height: 135px"/>
                        <h3 class="am-gallery-title">唐诗三百首 - 文学星空</h3>
                    </a>
                </div>
            </li>
            <li>
                <div class="am-gallery-item">
                    <a href="https://www.eeeaaa.cn/ciqu/chapter_18_1.html" title="宋词三百首 文学星空">
                        <img src="/images/index/sc.jpeg" alt="宋词三百首 文学星空" style="height: 135px"/>
                        <h3 class="am-gallery-title">宋词三百首 - 文学星空</h3>
                    </a>
                </div>
            </li>
            <li>
                <div class="am-gallery-item">
                    <a href="https://www.eeeaaa.cn/ciqu/chapter_19_1.html" title="元曲三百首 文学星空">
                        <img src="/images/index/yq.jpeg" alt="元曲三百首 文学星空" style="height: 135px"/>
                        <h3 class="am-gallery-title">元曲三百首 - 文学星空</h3>
                    </a>
                </div>
            </li>
            <li>
                <div class="am-gallery-item">
                    <a href="<?=$this->web_url?>/wenyanwen/list_5.html" title="文言文 文学星空">
                        <img src="/images/index/wyw.jpg" alt="文言文 文学星空" style="height: 135px"/>
                        <h3 class="am-gallery-title">文言文 - 文学星空</h3>
                    </a>
                </div>
            </li>
        </ul>
    </div>
    <!--诗文词曲-->
    <div class="am-container">
        <div data-am-widget="titlebar" class="am-titlebar am-titlebar-default index-title">
            <h2 class="am-titlebar-title">诗文词曲</h2>
            <nav class="am-titlebar-nav">
                <a href="https://www.eeeaaa.cn/tangshi/list_1.html" title="唐诗" class="link">唐诗</a>
                <a href="<?=$this->web_url?>/ciqu/list_2.html" title="宋词" class="link">宋词</a>
                <a href="<?=$this->web_url?>/ciqu/list_4.html" title="元曲" class="link">元曲</a>

            </nav>
        </div>
        <div data-am-widget="tabs" class="am-tabs am-tabs-d2">
            <ul class="am-tabs-nav am-cf">
                <li class="am-active"><a href="[data-tab-panel-0]">唐诗</a></li>
                <li class=""><a href="[data-tab-panel-1]">宋词</a></li>
                <li class=""><a href="[data-tab-panel-2]">元曲</a></li>

            </ul>
            <div class="am-tabs-bd">
                <div data-tab-panel-0 class="am-tab-panel am-active">
                    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
                        <ul class="am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-thumbnails am-list am-list-striped mb0">
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/tangshi/chapter_15_1.html" title="唐诗三百首-1"><i class="am-icon-book am-icon-fw"></i> 唐诗三百首-1</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/tangshi/chapter_17_1.html" title="唐诗三百首-2"><i class="am-icon-book am-icon-fw"></i> 唐诗三百首-2</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/tangshi/chapter_16_1.html" title="全唐诗"><i class="am-icon-book am-icon-fw"></i> 全唐诗</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/tangshi/gushi_1_1.html" title="李白"><i class="am-icon-book am-icon-fw"></i> 李白</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/tangshi/gushi_3_1.html" title="杜甫"><i class="am-icon-book am-icon-fw"></i> 杜甫</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/tangshi/gushi_2_1.html" title="白居易"><i class="am-icon-book am-icon-fw"></i> 白居易</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/tangshi/gushi_4_1.html" title="王维"><i class="am-icon-book am-icon-fw"></i> 王维</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/tangshi/gushi_5_1.html" title="刘禹锡"><i class="am-icon-book am-icon-fw"></i> 刘禹锡</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/tangshi/gushi_6_1.html" title="李商隐"><i class="am-icon-book am-icon-fw"></i> 李商隐</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/tangshi/gushi_7_1.html" title="杜牧"><i class="am-icon-book am-icon-fw"></i> 杜牧</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/tangshi/gushi_8_1.html" title="孟浩然"><i class="am-icon-book am-icon-fw"></i> 孟浩然</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/tangshi/gushi_9_1.html" title="元稹"><i class="am-icon-book am-icon-fw"></i> 元稹</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/tangshi/gushi_10_1.html" title="柳宗元"><i class="am-icon-book am-icon-fw"></i> 柳宗元</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/tangshi/gushi_11_1.html" title="韩愈"><i class="am-icon-book am-icon-fw"></i> 韩愈</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/tangshi/gushi_12_1.html" title="岑参"><i class="am-icon-book am-icon-fw"></i> 岑参</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/tangshi/gushi_15_1.html" title="温庭筠"><i class="am-icon-book am-icon-fw"></i> 温庭筠</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/tangshi/gushi_18_1.html" title="王昌龄"><i class="am-icon-book am-icon-fw"></i> 王昌龄</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/tangshi/gushi_36_1.html" title="贺知章"><i class="am-icon-book am-icon-fw"></i> 贺知章</a></li>
                        </ul>
                    </div>
                </div>
                <div data-tab-panel-1 class="am-tab-panel ">
                    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
                        <ul class="am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-thumbnails am-list am-list-striped mb0">
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/chapter_18_1.html" title="宋词三百首"><i class="am-icon-book am-icon-fw"></i> 宋词三百首</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/songci_58_1.html" title="苏轼"><i class="am-icon-book am-icon-fw"></i> 苏轼</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/songci_59_1.html" title="辛弃疾"><i class="am-icon-book am-icon-fw"></i> 辛弃疾</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/songci_60_1.html" title="李清照"><i class="am-icon-book am-icon-fw"></i> 李清照</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/songci_61_1.html" title="陆游"><i class="am-icon-book am-icon-fw"></i> 陆游</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/songci_62_1.html" title="王安石"><i class="am-icon-book am-icon-fw"></i> 王安石</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/songci_63_1.html" title="欧阳修"><i class="am-icon-book am-icon-fw"></i> 欧阳修</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/songci_64_1.html" title="柳永"><i class="am-icon-book am-icon-fw"></i> 柳永</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/songci_65_1.html" title="杨万里"><i class="am-icon-book am-icon-fw"></i> 杨万里</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/songci_66_1.html" title="范仲淹"><i class="am-icon-book am-icon-fw"></i> 范仲淹</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/songci_67_1.html" title="晏殊"><i class="am-icon-book am-icon-fw"></i> 晏殊</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/songci_68_1.html" title="岳飞"><i class="am-icon-book am-icon-fw"></i> 岳飞</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/songci_69_1.html" title="晏几道"><i class="am-icon-book am-icon-fw"></i> 晏几道</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/songci_70_1.html" title="周邦彦"><i class="am-icon-book am-icon-fw"></i> 周邦彦</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/songci_71_1.html" title="秦观"><i class="am-icon-book am-icon-fw"></i> 秦观</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/songci_72_1.html" title="朱熹"><i class="am-icon-book am-icon-fw"></i> 朱熹</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/songci_73_1.html" title="吴文英"><i class="am-icon-book am-icon-fw"></i> 吴文英</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/songci_74_1.html" title="黄庭坚"><i class="am-icon-book am-icon-fw"></i> 黄庭坚</a></li>
                        </ul>
                    </div>
                </div>
                <div data-tab-panel-2 class="am-tab-panel ">
                    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
                        <ul class="am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-thumbnails am-list am-list-striped mb0">
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/chapter_19_1.html" title="元曲三百首"><i class="am-icon-book am-icon-fw"></i> 元曲三百首</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/yuanqu_87_1.html" title="马致远"><i class="am-icon-book am-icon-fw"></i> 马致远</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/yuanqu_88_1.html" title="白朴"><i class="am-icon-book am-icon-fw"></i> 白朴</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/yuanqu_89_1.html" title="王冕"><i class="am-icon-book am-icon-fw"></i> 王冕</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/yuanqu_90_1.html" title="张可久"><i class="am-icon-book am-icon-fw"></i> 张可久</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/yuanqu_91_1.html" title="张养浩"><i class="am-icon-book am-icon-fw"></i> 张养浩</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/yuanqu_92_1.html" title="关汉卿"><i class="am-icon-book am-icon-fw"></i> 关汉卿</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/yuanqu_93_1.html" title="徐再思"><i class="am-icon-book am-icon-fw"></i> 徐再思</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/yuanqu_94_1.html" title="乔吉"><i class="am-icon-book am-icon-fw"></i> 乔吉</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/yuanqu_95_1.html" title="贯云石"><i class="am-icon-book am-icon-fw"></i> 贯云石</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/yuanqu_96_1.html" title="薛昂夫"><i class="am-icon-book am-icon-fw"></i> 薛昂夫</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/yuanqu_97_1.html" title="李致远"><i class="am-icon-book am-icon-fw"></i> 李致远</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/yuanqu_98_1.html" title="周文质"><i class="am-icon-book am-icon-fw"></i> 周文质</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/yuanqu_99_1.html" title="卢挚"><i class="am-icon-book am-icon-fw"></i> 卢挚</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/yuanqu_100_1.html" title="施耐庵"><i class="am-icon-book am-icon-fw"></i> 施耐庵</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/yuanqu_101_1.html" title="王实甫"><i class="am-icon-book am-icon-fw"></i> 王实甫</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/yuanqu_104_1.html" title="王和卿"><i class="am-icon-book am-icon-fw"></i> 王和卿</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/yuanqu_109_1.html" title="罗贯中"><i class="am-icon-book am-icon-fw"></i> 罗贯中</a></li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!--短文小说-->
<!--    <div class="am-container">-->
<!--        <div data-am-widget="titlebar" class="am-titlebar am-titlebar-default index-title">-->
<!--            <h2 class="am-titlebar-title">短文小说</h2>-->
<!--            <nav class="am-titlebar-nav">-->
<!--                <a href="https://www.eeeaaa.cn/xiaoshuo/wuxia_1.html" title="武侠小说" class="link">武侠</a>-->
<!--                <a href="https://www.eeeaaa.cn/xiaoshuo/yanqing_2.html" title="言情小说" class="link">言情</a>-->
<!--                <a href="https://www.eeeaaa.cn/xiaoshuo/xiaoyuan_4.html" title="校园小说" class="link">校园</a>-->
<!--                <a href="https://www.eeeaaa.cn/xiaoshuo/xuanhuan_5.html" title="玄幻小说" class="link">玄幻</a>-->
<!--                <a href="https://www.eeeaaa.cn/xiaoshuo/wangluo_6.html" title="网络小说" class="link">网络</a>-->
<!--                <a href="https://www.eeeaaa.cn/xiaoshuo/xiandai_3.html" title="现代小说" class="link">现代</a>-->
<!--            </nav>-->
<!--        </div>-->
<!--        <div data-am-widget="tabs" class="am-tabs am-tabs-d2">-->
<!--            <ul class="am-tabs-nav am-cf">-->
<!--                <li class="am-active"><a href="[data-tab-panel-0]">武侠</a></li>-->
<!--                <li class=""><a href="[data-tab-panel-1]">言情</a></li>-->
<!--                <li class=""><a href="[data-tab-panel-2]">校园</a></li>-->
<!--                <li class=""><a href="[data-tab-panel-3]">玄幻</a></li>-->
<!--                <li class=""><a href="[data-tab-panel-4]">网络</a></li>-->
<!--                <li class=""><a href="[data-tab-panel-5]">现代</a></li>-->
<!--            </ul>-->
<!--            <div class="am-tabs-bd">-->
<!--                <div data-tab-panel-0 class="am-tab-panel am-active">-->
<!--                    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">-->
<!--                        <ul class="am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-thumbnails am-list am-list-striped mb0">-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_1_1.html" title="金庸"><i class="am-icon-book am-icon-fw"></i> 金庸</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_2_1.html" title="古龙"><i class="am-icon-book am-icon-fw"></i> 古龙</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_6_1.html" title="梁羽生"><i class="am-icon-book am-icon-fw"></i> 梁羽生</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_18_1.html" title="松柏生"><i class="am-icon-book am-icon-fw"></i> 松柏生</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_21_1.html" title="卧龙生"><i class="am-icon-book am-icon-fw"></i> 卧龙生</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_25_1.html" title="柳残阳"><i class="am-icon-book am-icon-fw"></i> 柳残阳</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_28_1.html" title="诸葛青云"><i class="am-icon-book am-icon-fw"></i> 诸葛青云</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_31_1.html" title="陈青云"><i class="am-icon-book am-icon-fw"></i> 陈青云</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_32_1.html" title="云中岳"><i class="am-icon-book am-icon-fw"></i> 云中岳</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_33_1.html" title="曹若冰"><i class="am-icon-book am-icon-fw"></i> 曹若冰</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_34_1.html" title="李凉"><i class="am-icon-book am-icon-fw"></i> 李凉</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_35_1.html" title="萧逸"><i class="am-icon-book am-icon-fw"></i> 萧逸</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_36_1.html" title="独孤红"><i class="am-icon-book am-icon-fw"></i> 独孤红</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_37_1.html" title="宫白羽"><i class="am-icon-book am-icon-fw"></i> 宫白羽</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_38_1.html" title="石玉昆"><i class="am-icon-book am-icon-fw"></i> 石玉昆</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_46_1.html" title="墨余生"><i class="am-icon-book am-icon-fw"></i> 墨余生</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_47_1.html" title="平江不肖生"><i class="am-icon-book am-icon-fw"></i> 平江不肖生</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_48_1.html" title="秋梦痕"><i class="am-icon-book am-icon-fw"></i> 秋梦痕</a></li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div data-tab-panel-1 class="am-tab-panel ">-->
<!--                    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">-->
<!--                        <ul class="am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-thumbnails am-list am-list-striped mb0">-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_4_1.html" title="张爱玲"><i class="am-icon-book am-icon-fw"></i> 张爱玲</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_3_1.html" title="席绢"><i class="am-icon-book am-icon-fw"></i> 席绢</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_5_1.html" title="辛夷坞"><i class="am-icon-book am-icon-fw"></i> 辛夷坞</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_7_1.html" title="唐七公子"><i class="am-icon-book am-icon-fw"></i> 唐七公子</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_15_1.html" title="匪我思存"><i class="am-icon-book am-icon-fw"></i> 匪我思存</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_17_1.html" title="亦舒"><i class="am-icon-book am-icon-fw"></i> 亦舒</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_23_1.html" title="古灵"><i class="am-icon-book am-icon-fw"></i> 古灵</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_27_1.html" title="八月长安"><i class="am-icon-book am-icon-fw"></i> 八月长安</a></li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div data-tab-panel-2 class="am-tab-panel ">-->
<!--                    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">-->
<!--                        <ul class="am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-thumbnails am-list am-list-striped mb0">-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_8_1.html" title="郭敬明"><i class="am-icon-book am-icon-fw"></i> 郭敬明</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_9_1.html" title="顾漫"><i class="am-icon-book am-icon-fw"></i> 顾漫</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_16_1.html" title="三毛"><i class="am-icon-book am-icon-fw"></i> 三毛</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_39_1.html" title="韩寒"><i class="am-icon-book am-icon-fw"></i> 韩寒</a></li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div data-tab-panel-3 class="am-tab-panel ">-->
<!--                    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">-->
<!--                        <ul class="am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-thumbnails am-list am-list-striped mb0">-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_10_1.html" title="唐家三少"><i class="am-icon-book am-icon-fw"></i> 唐家三少</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_11_1.html" title="萧鼎"><i class="am-icon-book am-icon-fw"></i> 萧鼎</a></li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div data-tab-panel-4 class="am-tab-panel ">-->
<!--                    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">-->
<!--                        <ul class="am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-thumbnails am-list am-list-striped mb0">-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_20_1.html" title="天蚕土豆"><i class="am-icon-book am-icon-fw"></i> 天蚕土豆</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_14_1.html" title="海宴"><i class="am-icon-book am-icon-fw"></i> 海宴</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_13_1.html" title="烽火戏诸侯"><i class="am-icon-book am-icon-fw"></i> 烽火戏诸侯</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_12_1.html" title="流潋紫"><i class="am-icon-book am-icon-fw"></i> 流潋紫</a></li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div data-tab-panel-5 class="am-tab-panel ">-->
<!--                    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">-->
<!--                        <ul class="am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-thumbnails am-list am-list-striped mb0">-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_30_1.html" title="鲁迅"><i class="am-icon-book am-icon-fw"></i> 鲁迅</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_52_1.html" title="沈从文"><i class="am-icon-book am-icon-fw"></i> 沈从文</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_41_1.html" title="老舍"><i class="am-icon-book am-icon-fw"></i> 老舍</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_19_1.html" title="王朔"><i class="am-icon-book am-icon-fw"></i> 王朔</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_22_1.html" title="莫言"><i class="am-icon-book am-icon-fw"></i> 莫言</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_24_1.html" title="路遥"><i class="am-icon-book am-icon-fw"></i> 路遥</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_29_1.html" title="贾平凹"><i class="am-icon-book am-icon-fw"></i> 贾平凹</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_58_1.html" title="茅盾"><i class="am-icon-book am-icon-fw"></i> 茅盾</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_59_1.html" title="巴金"><i class="am-icon-book am-icon-fw"></i> 巴金</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_60_1.html" title="汪曾祺"><i class="am-icon-book am-icon-fw"></i> 汪曾祺</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_53_1.html" title="陈忠实"><i class="am-icon-book am-icon-fw"></i> 陈忠实</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_54_1.html" title="苏童"><i class="am-icon-book am-icon-fw"></i> 苏童</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_55_1.html" title="阿城"><i class="am-icon-book am-icon-fw"></i> 阿城</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_57_1.html" title="铁凝"><i class="am-icon-book am-icon-fw"></i> 铁凝</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_61_1.html" title="王安忆"><i class="am-icon-book am-icon-fw"></i> 王安忆</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_43_1.html" title="凌力"><i class="am-icon-book am-icon-fw"></i> 凌力</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_42_1.html" title="张恨水"><i class="am-icon-book am-icon-fw"></i> 张恨水</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_45_1.html" title="高阳"><i class="am-icon-book am-icon-fw"></i> 高阳</a></li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
    <!--古文典籍-->
    <div class="am-container">
        <div data-am-widget="titlebar" class="am-titlebar am-titlebar-default index-title">
            <h2 class="am-titlebar-title">古文典籍</h2>
            <nav class="am-titlebar-nav">
                <a href="<?=$this->web_url?>/wenyanwen/list_5.html" title="文言文" class="link">文言文</a>
                <a href="https://www.eeeaaa.cn/gudian/gudian_7.html" title="古典小说" class="link">古典小说</a>
            </nav>
        </div>
        <div data-am-widget="tabs" class="am-tabs am-tabs-d2">
            <ul class="am-tabs-nav am-cf">
                <li class="am-active"><a href="[data-tab-panel-1]">文言文</a></li>
                <li class=""><a href="[data-tab-panel-0]">古典小说</a></li>
            </ul>
            <div class="am-tabs-bd">
                <div data-tab-panel-0 class="am-tab-panel am-active">
                    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
                        <ul class="am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-thumbnails am-list am-list-striped mb0">
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/wenyanwen/detail_46780.html" title="出师表"><i class="am-icon-book am-icon-fw"></i> 出师表</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/wenyanwen/detail_47102.html" title="赤壁赋"><i class="am-icon-book am-icon-fw"></i> 赤壁赋</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/wenyanwen/detail_46781.html" title="岳阳楼记"><i class="am-icon-book am-icon-fw"></i> 岳阳楼记</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/wenyanwen/detail_47103.html" title="阿房宫赋"><i class="am-icon-book am-icon-fw"></i> 阿房宫赋</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/wenyanwen/detail_46782.html" title="醉翁亭记"><i class="am-icon-book am-icon-fw"></i> 醉翁亭记</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/wenyanwen/detail_46784.html" title="兰亭集序"><i class="am-icon-book am-icon-fw"></i> 兰亭集序</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/wenyanwen/detail_46785.html" title="隆中对"><i class="am-icon-book am-icon-fw"></i> 隆中对</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/wenyanwen/detail_47107.html" title="登徒子好色赋"><i class="am-icon-book am-icon-fw"></i> 登徒子好色赋</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/wenyanwen/detail_46791.html" title="桃花源记"><i class="am-icon-book am-icon-fw"></i> 桃花源记</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/wenyanwen/detail_46794.html" title="诫子书"><i class="am-icon-book am-icon-fw"></i> 诫子书</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/wenyanwen/detail_46789.html" title="湖心亭看雪"><i class="am-icon-book am-icon-fw"></i> 湖心亭看雪</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/wenyanwen/detail_46796.html" title="朱子家训"><i class="am-icon-book am-icon-fw"></i> 朱子家训</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/wenyanwen/detail_46808.html" title="进学解"><i class="am-icon-book am-icon-fw"></i> 进学解</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/wenyanwen/detail_46821.html" title="人间词话七则"><i class="am-icon-book am-icon-fw"></i> 人间词话七则</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/wenyanwen/detail_46835.html" title="谏逐客书"><i class="am-icon-book am-icon-fw"></i> 谏逐客书</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/wenyanwen/detail_46858.html" title="与友人书"><i class="am-icon-book am-icon-fw"></i> 与友人书</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/ciqu/detail_23758.html" title="游褒禅山记"><i class="am-icon-book am-icon-fw"></i> 游褒禅山记</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/wenyanwen/detail_47061.html" title="曾国藩诫子书"><i class="am-icon-book am-icon-fw"></i> 曾国藩诫子书</a></li>
                        </ul>
                    </div>
                </div>
                <div data-tab-panel-1 class="am-tab-panel ">
                    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
                        <ul class="am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-thumbnails am-list am-list-striped mb0">
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/gudian/chapter_1504_1.html" title="三国演义"><i class="am-icon-book am-icon-fw"></i> 三国演义</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/gudian/chapter_1505_1.html" title="水浒传"><i class="am-icon-book am-icon-fw"></i> 水浒传</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/gudian/chapter_1506_1.html" title="西游记"><i class="am-icon-book am-icon-fw"></i> 西游记</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/gudian/chapter_1507_1.html" title="红楼梦"><i class="am-icon-book am-icon-fw"></i> 红楼梦</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/gudian/chapter_1520_1.html" title="金瓶梅传奇"><i class="am-icon-book am-icon-fw"></i> 金瓶梅传奇</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/gudian/chapter_1508_1.html" title="儒林外史"><i class="am-icon-book am-icon-fw"></i> 儒林外史</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/gudian/chapter_1514_1.html" title="醒世恒言"><i class="am-icon-book am-icon-fw"></i> 醒世恒言</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/gudian/chapter_1515_1.html" title="警世通言"><i class="am-icon-book am-icon-fw"></i> 警世通言</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/gudian/chapter_1522_1.html" title="喻世明言"><i class="am-icon-book am-icon-fw"></i> 喻世明言</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/gudian/chapter_1513_1.html" title="初刻拍案惊奇"><i class="am-icon-book am-icon-fw"></i> 初刻拍案惊奇</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/gudian/chapter_1518_1.html" title="二刻拍案惊奇"><i class="am-icon-book am-icon-fw"></i> 二刻拍案惊奇</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/gudian/chapter_1509_1.html" title="官场现形记"><i class="am-icon-book am-icon-fw"></i> 官场现形记</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/gudian/chapter_1521_1.html" title="20年目睹之怪现状"><i class="am-icon-book am-icon-fw"></i> 20年目睹之怪现状</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/gudian/chapter_1516_1.html" title="镜花缘"><i class="am-icon-book am-icon-fw"></i> 镜花缘</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/gudian/chapter_1510_1.html" title="孽海花"><i class="am-icon-book am-icon-fw"></i> 孽海花</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/gudian/chapter_1517_1.html" title="绿野仙踪"><i class="am-icon-book am-icon-fw"></i> 绿野仙踪</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/gudian/chapter_1512_1.html" title="老残游记"><i class="am-icon-book am-icon-fw"></i> 老残游记</a></li>
                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/gudian/chapter_1519_1.html" title="济公全传"><i class="am-icon-book am-icon-fw"></i> 济公全传</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--首页 wap-->
    <div class="am-container">
        <div class="_2k5i461ly2x"></div>
        <script type="text/javascript">
            var ua = navigator.userAgent;
            if (ua.indexOf('Android') > -1 || ua.indexOf('iPhone') > -1 || ua.indexOf('iPod') > -1 || ua.indexOf('Symbian') > -1){
                (window.slotbydup = window.slotbydup || []).push({
                    id: "u6033315",
                    container: "_2k5i461ly2x",
                    async: true
                });
            }
        </script>
    </div>
    <!--首页 pc-->
    <div class="am-container">
        <div class="_eevbx2me1qw"></div>
        <script type="text/javascript">
            var ua = navigator.userAgent;
            if (ua.indexOf('Android') > -1 || ua.indexOf('iPhone') > -1 || ua.indexOf('iPod') > -1 || ua.indexOf('Symbian') > -1){
            }else{
                (window.slotbydup = window.slotbydup || []).push({
                    id: "u6033342",
                    container: "_eevbx2me1qw",
                    async: true
                });
            }
        </script>
    </div>


<?php $this->display('section/footer.phtml');?>