<!DOCTYPE HTML>
<html>
<head>
<title>Home</title>
<meta name="keywords" content="Fundaaz Iphone web template, Andriod web template, Smartphone web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="/css/style.css" rel="stylesheet" type="text/css"  media="all" />
</head>
<body>
<div class="wrap">
<div class="header">
	<div class="logo"><a href="index.html"><img src="/images/logo.png" /></a></div>
    <div class="search">
    	<form>
        	<input type="text" value="" />
        	<input type="submit" value="" />
        </form>
    </div>
    <div class="social">
    	<ul>
        	<li>Follow us</li>
            <li><a href="#"><span class="icon facebook"></span></a></li>
            <li><a href="#"><span class="icon twitter"></span></a></li>
            <li><a href="#"><span class="icon fav"></span></a></li>
        </ul>
    </div>
    <div class="clear"></div>
</div>
<div class="content">
    <div class="sidebar">
    	<div class="side">
            <h3>作者</h3>
            <ul>
                <?php foreach($this->author_list as $value){?>
                <li><a href="category.html"><?=$value['author_name']?></a></li>
                <?php }?>
            </ul>
        </div>
        <div class="side">
            <h3>最新</h3>
            <ul>
                <?php foreach($this->novel_list as $value){?>
                    <li><a href="category.html"><?=$value['name']?></a></li>
                <?php }?>
            </ul>
        </div>
    </div>
    <div class="nav">
                <ul>
                    <li><a href="#">言情</a></li>
                    <li><a href="#">武侠</a></li>
                    <li><a href="#">现代</a></li>
                    <li><a href="#">剧情</a></li>
                </ul>
            </div>
	<div class="main">
        <div class="grid">
        	<div class="prev"><a href="single.html"><img src="" alt="" /></a></div>
            <ul class="details">
                <li><a href="single.html">Corporate WebSites</a></li>
                <li><a href="#">Html</a></li>
                <li><a href="#">Css</a></li>
                <li><a href="#">Images</a></li>
                <li><a href="#">More</a></li>
            </ul>
            <div class="clear"></div>
        </div>
        <div class="grid">
        	<div class="prev"><a href="#"><img src="http://lorempixel.com/150/150/food/" alt="" /></a></div>
            <ul class="details">
                <li><a href="#">Corporate WebSites</a></li>
                <li><a href="#">Html</a></li>
                <li><a href="#">Css</a></li>
                <li><a href="#">Images</a></li>
                <li><a href="#">More</a></li>
            </ul>
            <div class="clear"></div>
        </div>
        <div class="grid">
        	<div class="prev"><a href="#"><img src="http://lorempixel.com/150/150/food/" alt="" /></a></div>
            <ul class="details">
                <li><a href="#">Corporate WebSites</a></li>
                <li><a href="#">Html</a></li>
                <li><a href="#">Css</a></li>
                <li><a href="#">Images</a></li>
                <li><a href="#">More</a></li>
            </ul>
            <div class="clear"></div>
        </div>
        <div class="grid">
        	<div class="prev"><a href="#"><img src="http://lorempixel.com/150/150/food/" alt="" /></a></div>
            <ul class="details">
                <li><a href="#">Corporate WebSites</a></li>
                <li><a href="#">Html</a></li>
                <li><a href="#">Css</a></li>
                <li><a href="#">Images</a></li>
                <li><a href="#">More</a></li>
            </ul>
            <div class="clear"></div>
        </div>
        <div class="grid">
        	<div class="prev"><a href="#"><img src="http://lorempixel.com/150/150/food/" alt="" /></a></div>
            <ul class="details">
                <li><a href="#">Corporate WebSites</a></li>
                <li><a href="#">Html</a></li>
                <li><a href="#">Css</a></li>
                <li><a href="#">Images</a></li>
                <li><a href="#">More</a></li>
            </ul>
            <div class="clear"></div>
        </div>
        <div class="grid">
        	<div class="prev"><a href="#"><img src="http://lorempixel.com/150/150/food/" alt="" /></a></div>
            <ul class="details">
                <li><a href="#">Corporate WebSites</a></li>
                <li><a href="#">Html</a></li>
                <li><a href="#">Css</a></li>
                <li><a href="#">Images</a></li>
                <li><a href="#">More</a></li>
            </ul>
            <div class="clear"></div>
        </div>
        <div class="grid">
        	<div class="prev"><a href="#"><img src="http://lorempixel.com/150/150/food/" alt="" /></a></div>
            <ul class="details">
                <li><a href="#">Corporate WebSites</a></li>
                <li><a href="#">Html</a></li>
                <li><a href="#">Css</a></li>
                <li><a href="#">Images</a></li>
                <li><a href="#">More</a></li>
            </ul>
            <div class="clear"></div>
        </div>
        <div class="grid">
        	<div class="prev"><a href="#"><img src="http://lorempixel.com/150/150/food/" alt="" /></a></div>
            <ul class="details">
                <li><a href="#">Corporate WebSites</a></li>
                <li><a href="#">Html</a></li>
                <li><a href="#">Css</a></li>
                <li><a href="#">Images</a></li>
                <li><a href="#">More</a></li>
            </ul>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
</div>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/" >企业网站模板</a></div>
<!--------------------------------------->
<div class="wrap">
<div id="bg_footer">	
    <div id="footer">
        <div class="column-4-1">
            <h3>Fundaaz</h3>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="feedback.html">Contact us</a></li>
                <li><a href="#">Help</a></li>
                <li><a href="#">Links</a></li>
                <li><a href="#">Sitemap</a></li>
            </ul>
        </div>
        <div class="column-4-1">
            <h3>Fundaaz</h3>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="feedback.html">Contact us</a></li>
                <li><a href="#">Help</a></li>
                <li><a href="#">Links</a></li>
                <li><a href="#">Sitemap</a></li>
            </ul>
        </div>
        <div class="column-4-1">
            <h3>Fundaaz</h3>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="feedback.html">Contact us</a></li>
                <li><a href="#">Help</a></li>
                <li><a href="#">Links</a></li>
                <li><a href="#">Sitemap</a></li>
            </ul>
        </div>
        <div class="column-4-1">
            <h3>Fundaaz</h3>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="feedback.html">Contact us</a></li>
                <li><a href="#">Help</a></li>
                <li><a href="#">Links</a></li>
                <li><a href="#">Sitemap</a></li>
            </ul>
        </div>
    </div>
    <div class="clear"></div>
    <div class="copy">Copyright &copy; 2015.Company name All rights reserved.<a target="_blank" href="http://www.cssmoban.com/">&#x7F51;&#x9875;&#x6A21;&#x677F;</a></div>
</div>
</div>
</body>
</html>
