<?php $this->display('section/header.phtml');?>
    <?php if(!empty($this->wenxue_list['recommend_tang'])){?>
    <h2 class="star am-container mcenter"><span><img src="images/star.png" alt="隋唐文学">隋唐文学</span></h2>
    <div class="am-container">
        <ul data-am-widget="gallery" class="am-gallery am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-gallery-bordered" data-am-gallery="{  }" >
            <?php foreach ($this->wenxue_list['recommend_tang'] as $value){?>
                <li>
                    <div class="cattlist_0">
                        <div class="cattlist_1">
                            <div class="am-g">
                                <div class="am-u-sm-4 am-u-md-5 am-u-lg-5 am-vertical-align">
                                    <div class="am-vertical-align-middle">
                                        <img src="<?=$value['pic']?:\YC\Common::getUrl('')?>" alt="<?=$value['author_name']?>">
                                    </div>
                                </div>
                                <div class="am-u-sm-8 am-u-md-7 am-u-lg-7">
                                    <h2><?=$value['author_name']?></h2>
                                </div>
                            </div>
                        </div>
                        <div class="cattlist_2">
                            <p><?=$value['description']?></p>
                        </div>
                        <div class="cattlist_3">
                            <a class="am-btn am-btn-warning" title="<?=$value['author_name']?>" href="<?=$this->web_url?>/tangshi/gushi_<?=$value['id']?>_1.html">开始阅读</a>
                        </div>
                    </div>
                </li>
            <?php }?>

        </ul>
        <a class="am-btn am-btn-default am-btn-block mtb20" title="查看更多隋唐文学" href="<?=$this->web_url?>/tangshi/list_<?=ArticlesTypeModel::ARTICLE_TYPE_TANG?>.html">查看更多隋唐文学</a>
    </div>
    <?php }?>

<h2 class="star am-container mcenter"><span><img src="images/star.png" alt="武侠小说">武侠小说</span></h2>
<div class="am-container">
    <ul data-am-widget="gallery" class="am-gallery am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-gallery-bordered" data-am-gallery="{  }" >
        <?php foreach ($this->wuxia_list as $value){?>
        <li>
            <div class="am-gallery-item">
                <a href="<?=$this->web_url?>/xiaoshuo/chapter_<?=$value['id']?>_1.html" class="" title="<?=$value['name']?>">
                    <img src="<?=empty($value['pic']) ? \YC\Common::getUrl($value['pic']) : $value['pic']?>" alt="<?=$value['name']?>" class="index_img"/>
                    <h3 class="am-gallery-title"><?=$value['name']?></h3>
                    <div class="am-gallery-desc"><?=$value['author_name']?></div>
                </a>
            </div>
        </li>
    <?php }?>

    </ul>
    <a class="am-btn am-btn-default am-btn-block mtb20" title="查看更多武侠小说" href="<?=$this->web_url?>/xiaoshuo/wuxia_<?=NovelModel::NOVEL_CLASS_WUXIA?>.html">查看更多武侠小说</a>
</div>

    <h2 class="star am-container mcenter"><span><img src="images/star.png" alt="言情小说">言情小说</span></h2>
    <div class="am-container">
        <ul data-am-widget="gallery" class="am-gallery am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-gallery-bordered" data-am-gallery="{  }" >
            <?php foreach ($this->yanqing_list as $value){?>
                <li>
                    <div class="am-gallery-item">
                        <a href="<?=$this->web_url?>/xiaoshuo/chapter_<?=$value['id']?>_1.html" class="" title="<?=$value['name']?>">
                            <img src="<?=empty($value['pic']) ? \YC\Common::getUrl($value['pic']) : $value['pic']?>" alt="<?=$value['name']?>" class="index_img"/>
                            <h3 class="am-gallery-title"><?=$value['name']?></h3>
                            <div class="am-gallery-desc"><?=$value['author_name']?></div>
                        </a>
                    </div>
                </li>
            <?php }?>

        </ul>
        <a class="am-btn am-btn-default am-btn-block mtb20" title="查看更多言情小说" href="<?=$this->web_url?>/xiaoshuo/yanqing_<?=NovelModel::NOVEL_CLASS_YANQING?>.html">查看更多言情小说</a>
    </div>
    <h2 class="star am-container mcenter"><span><img src="images/star.png" alt="校园小说">校园小说</span></h2>
    <div class="am-container">
        <ul data-am-widget="gallery" class="am-gallery am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-gallery-bordered" data-am-gallery="{  }" >
            <?php foreach ($this->xiaoyuan_list as $value){?>
                <li>
                    <div class="am-gallery-item">
                        <a href="<?=$this->web_url?>/xiaoshuo/chapter_<?=$value['id']?>_1.html" class="" title="<?=$value['name']?>">
                            <img src="<?=empty($value['pic']) ? \YC\Common::getUrl($value['pic']) : $value['pic']?>" alt="<?=$value['name']?>" class="index_img"/>
                            <h3 class="am-gallery-title"><?=$value['name']?></h3>
                            <div class="am-gallery-desc"><?=$value['author_name']?></div>
                        </a>
                    </div>
                </li>
            <?php }?>

        </ul>
        <a class="am-btn am-btn-default am-btn-block mtb20" title="查看更多校园小说" href="<?=$this->web_url?>/xiaoshuo/xiaoyuan_<?=NovelModel::NOVEL_CLASS_SCHOOL?>.html">查看更多校园小说</a>
    </div>
    <h2 class="star am-container mcenter"><span><img src="images/star.png" alt="玄幻小说">玄幻小说</span></h2>
    <div class="am-container">
        <ul data-am-widget="gallery" class="am-gallery am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-gallery-bordered" data-am-gallery="{  }" >
            <?php foreach ($this->xuanhuan_list as $value){?>
                <li>
                    <div class="am-gallery-item">
                        <a href="<?=$this->web_url?>/xiaoshuo/chapter_<?=$value['id']?>_1.html" class="" title="<?=$value['name']?>">
                            <img src="<?=empty($value['pic']) ? \YC\Common::getUrl($value['pic']) : $value['pic']?>" alt="<?=$value['name']?>" class="index_img"/>
                            <h3 class="am-gallery-title"><?=$value['name']?></h3>
                            <div class="am-gallery-desc"><?=$value['author_name']?></div>
                        </a>
                    </div>
                </li>
            <?php }?>

        </ul>
        <a class="am-btn am-btn-default am-btn-block mtb20" title="查看更多玄幻小说" href="<?=$this->web_url?>/xiaoshuo/xuanhuan_<?=NovelModel::NOVEL_CLASS_FANTASY?>.html">查看更多玄幻小说</a>
    </div>
    <h2 class="star am-container mcenter"><span><img src="images/star.png" alt="网络小说">网络小说</span></h2>
    <div class="am-container">
        <ul data-am-widget="gallery" class="am-gallery am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-gallery-bordered" data-am-gallery="{  }" >
            <?php foreach ($this->wangluo_list as $value){?>
                <li>
                    <div class="am-gallery-item">
                        <a href="<?=$this->web_url?>/xiaoshuo/chapter_<?=$value['id']?>_1.html" class="" title="<?=$value['name']?>">
                            <img src="<?=empty($value['pic']) ? \YC\Common::getUrl($value['pic']) : $value['pic']?>" alt="<?=$value['name']?>" class="index_img"/>
                            <h3 class="am-gallery-title"><?=$value['name']?></h3>
                            <div class="am-gallery-desc"><?=$value['author_name']?></div>
                        </a>
                    </div>
                </li>
            <?php }?>

        </ul>
        <a class="am-btn am-btn-default am-btn-block mtb20" title="查看更多网络小说" href="<?=$this->web_url?>/xiaoshuo/wangluo_<?=NovelModel::NOVEL_CLASS_NET?>.html">查看更多网络小说</a>
    </div>



<?php $this->display('section/footer.phtml');?>