<!DOCTYPE HTML>
<html>
<head>
<title>Home</title>
<meta name="keywords" content="Fundaaz Iphone web template, Andriod web template, Smartphone web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="/css/style.css" rel="stylesheet" type="text/css"  media="all" />
</head>
<body>
<div class="wrap">
<div class="header">
	<div class="logo"><a href="index.html"><img src="/images/logo.png" /></a></div>
    <div class="search">
    	<form>
        	<input type="text" value="" />
        	<input type="submit" value="" />
        </form>
    </div>
    <div class="social">
    	<ul>
        	<li>Follow us</li>
            <li><a href="#"><span class="icon facebook"></span></a></li>
            <li><a href="#"><span class="icon twitter"></span></a></li>
            <li><a href="#"><span class="icon fav"></span></a></li>
        </ul>
    </div>
    <div class="clear"></div>
</div>
<div class="content">
    <div class="sidebar">
    	<div class="side">
            <h3>作者</h3>
            <ul>
                <?php foreach($this->author_list as $value){?>
                <li><a href="category.html"><?=$value['author_name']?></a></li>
                <?php }?>
            </ul>
        </div>
        <div class="side">
            <h3>最新</h3>
            <ul>
                <?php foreach($this->novel_list as $value){?>
                    <li><a href="/xiaoshuo/detail_<?=$value['id']?>".html><?=$value['name']?></a></li>
                <?php }?>
            </ul>
        </div>
    </div>
    <div class="nav">
                <ul>
                    <li><a href="#">言情</a></li>
                    <li><a href="#">武侠</a></li>
                    <li><a href="#">现代</a></li>
                    <li><a href="#">剧情</a></li>
                </ul>
            </div>
	<div class="main">
        <?php foreach($this->novel_list as $value){?>
        <div class="grid">
        	<div class="prev"><a href="/xiaoshuo/list_<?=$value['id']?>.html"><img src="" alt="" /></a></div>
            <ul class="details">
                <li><a href="/xiaoshuo/list_<?=$value['id']?>.html"><?=$value['name']?></a></li>
                <li><a href="/xiaoshuo/list_<?=$value['id']?>.html"><?=mb_substr($value['content'],0,80,"UTF-8")?></a></li>
            </ul>
            <div class="clear"></div>
        </div>
        <?php } ?>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
</div>
</div>
<!--------------------------------------->
<div class="wrap">
<div id="bg_footer">	
    <div id="footer">
        <div class="column-4-1">
            <h3>Fundaaz</h3>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="feedback.html">Contact us</a></li>
                <li><a href="#">Help</a></li>
                <li><a href="#">Links</a></li>
                <li><a href="#">Sitemap</a></li>
            </ul>
        </div>
        <div class="column-4-1">
            <h3>Fundaaz</h3>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="feedback.html">Contact us</a></li>
                <li><a href="#">Help</a></li>
                <li><a href="#">Links</a></li>
                <li><a href="#">Sitemap</a></li>
            </ul>
        </div>
        <div class="column-4-1">
            <h3>Fundaaz</h3>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="feedback.html">Contact us</a></li>
                <li><a href="#">Help</a></li>
                <li><a href="#">Links</a></li>
                <li><a href="#">Sitemap</a></li>
            </ul>
        </div>
        <div class="column-4-1">
            <h3>Fundaaz</h3>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="feedback.html">Contact us</a></li>
                <li><a href="#">Help</a></li>
                <li><a href="#">Links</a></li>
                <li><a href="#">Sitemap</a></li>
            </ul>
        </div>
    </div>
    <div class="clear"></div>
    <div class="copy">Copyright &copy; 2015.Company name All rights reserved.<a target="_blank" href="http://www.cssmoban.com/">&#x7F51;&#x9875;&#x6A21;&#x677F;</a></div>
</div>
</div>
</body>
</html>
<!--短文小说-->
<!--    <div class="am-container">-->
<!--        <div data-am-widget="titlebar" class="am-titlebar am-titlebar-default index-title">-->
<!--            <h2 class="am-titlebar-title">短文小说</h2>-->
<!--            <nav class="am-titlebar-nav">-->
<!--                <a href="https://www.eeeaaa.cn/xiaoshuo/wuxia_1.html" title="武侠小说" class="link">武侠</a>-->
<!--                <a href="https://www.eeeaaa.cn/xiaoshuo/yanqing_2.html" title="言情小说" class="link">言情</a>-->
<!--                <a href="https://www.eeeaaa.cn/xiaoshuo/xiaoyuan_4.html" title="校园小说" class="link">校园</a>-->
<!--                <a href="https://www.eeeaaa.cn/xiaoshuo/xuanhuan_5.html" title="玄幻小说" class="link">玄幻</a>-->
<!--                <a href="https://www.eeeaaa.cn/xiaoshuo/wangluo_6.html" title="网络小说" class="link">网络</a>-->
<!--                <a href="https://www.eeeaaa.cn/xiaoshuo/xiandai_3.html" title="现代小说" class="link">现代</a>-->
<!--            </nav>-->
<!--        </div>-->
<!--        <div data-am-widget="tabs" class="am-tabs am-tabs-d2">-->
<!--            <ul class="am-tabs-nav am-cf">-->
<!--                <li class="am-active"><a href="[data-tab-panel-0]">武侠</a></li>-->
<!--                <li class=""><a href="[data-tab-panel-1]">言情</a></li>-->
<!--                <li class=""><a href="[data-tab-panel-2]">校园</a></li>-->
<!--                <li class=""><a href="[data-tab-panel-3]">玄幻</a></li>-->
<!--                <li class=""><a href="[data-tab-panel-4]">网络</a></li>-->
<!--                <li class=""><a href="[data-tab-panel-5]">现代</a></li>-->
<!--            </ul>-->
<!--            <div class="am-tabs-bd">-->
<!--                <div data-tab-panel-0 class="am-tab-panel am-active">-->
<!--                    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">-->
<!--                        <ul class="am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-thumbnails am-list am-list-striped mb0">-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_1_1.html" title="金庸"><i class="am-icon-book am-icon-fw"></i> 金庸</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_2_1.html" title="古龙"><i class="am-icon-book am-icon-fw"></i> 古龙</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_6_1.html" title="梁羽生"><i class="am-icon-book am-icon-fw"></i> 梁羽生</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_18_1.html" title="松柏生"><i class="am-icon-book am-icon-fw"></i> 松柏生</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_21_1.html" title="卧龙生"><i class="am-icon-book am-icon-fw"></i> 卧龙生</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_25_1.html" title="柳残阳"><i class="am-icon-book am-icon-fw"></i> 柳残阳</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_28_1.html" title="诸葛青云"><i class="am-icon-book am-icon-fw"></i> 诸葛青云</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_31_1.html" title="陈青云"><i class="am-icon-book am-icon-fw"></i> 陈青云</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_32_1.html" title="云中岳"><i class="am-icon-book am-icon-fw"></i> 云中岳</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_33_1.html" title="曹若冰"><i class="am-icon-book am-icon-fw"></i> 曹若冰</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_34_1.html" title="李凉"><i class="am-icon-book am-icon-fw"></i> 李凉</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_35_1.html" title="萧逸"><i class="am-icon-book am-icon-fw"></i> 萧逸</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_36_1.html" title="独孤红"><i class="am-icon-book am-icon-fw"></i> 独孤红</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_37_1.html" title="宫白羽"><i class="am-icon-book am-icon-fw"></i> 宫白羽</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_38_1.html" title="石玉昆"><i class="am-icon-book am-icon-fw"></i> 石玉昆</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_46_1.html" title="墨余生"><i class="am-icon-book am-icon-fw"></i> 墨余生</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_47_1.html" title="平江不肖生"><i class="am-icon-book am-icon-fw"></i> 平江不肖生</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_48_1.html" title="秋梦痕"><i class="am-icon-book am-icon-fw"></i> 秋梦痕</a></li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div data-tab-panel-1 class="am-tab-panel ">-->
<!--                    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">-->
<!--                        <ul class="am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-thumbnails am-list am-list-striped mb0">-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_4_1.html" title="张爱玲"><i class="am-icon-book am-icon-fw"></i> 张爱玲</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_3_1.html" title="席绢"><i class="am-icon-book am-icon-fw"></i> 席绢</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_5_1.html" title="辛夷坞"><i class="am-icon-book am-icon-fw"></i> 辛夷坞</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_7_1.html" title="唐七公子"><i class="am-icon-book am-icon-fw"></i> 唐七公子</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_15_1.html" title="匪我思存"><i class="am-icon-book am-icon-fw"></i> 匪我思存</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_17_1.html" title="亦舒"><i class="am-icon-book am-icon-fw"></i> 亦舒</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_23_1.html" title="古灵"><i class="am-icon-book am-icon-fw"></i> 古灵</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_27_1.html" title="八月长安"><i class="am-icon-book am-icon-fw"></i> 八月长安</a></li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div data-tab-panel-2 class="am-tab-panel ">-->
<!--                    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">-->
<!--                        <ul class="am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-thumbnails am-list am-list-striped mb0">-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_8_1.html" title="郭敬明"><i class="am-icon-book am-icon-fw"></i> 郭敬明</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_9_1.html" title="顾漫"><i class="am-icon-book am-icon-fw"></i> 顾漫</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_16_1.html" title="三毛"><i class="am-icon-book am-icon-fw"></i> 三毛</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_39_1.html" title="韩寒"><i class="am-icon-book am-icon-fw"></i> 韩寒</a></li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div data-tab-panel-3 class="am-tab-panel ">-->
<!--                    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">-->
<!--                        <ul class="am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-thumbnails am-list am-list-striped mb0">-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_10_1.html" title="唐家三少"><i class="am-icon-book am-icon-fw"></i> 唐家三少</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_11_1.html" title="萧鼎"><i class="am-icon-book am-icon-fw"></i> 萧鼎</a></li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div data-tab-panel-4 class="am-tab-panel ">-->
<!--                    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">-->
<!--                        <ul class="am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-thumbnails am-list am-list-striped mb0">-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_20_1.html" title="天蚕土豆"><i class="am-icon-book am-icon-fw"></i> 天蚕土豆</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_14_1.html" title="海宴"><i class="am-icon-book am-icon-fw"></i> 海宴</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_13_1.html" title="烽火戏诸侯"><i class="am-icon-book am-icon-fw"></i> 烽火戏诸侯</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_12_1.html" title="流潋紫"><i class="am-icon-book am-icon-fw"></i> 流潋紫</a></li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div data-tab-panel-5 class="am-tab-panel ">-->
<!--                    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">-->
<!--                        <ul class="am-avg-sm-2 am-avg-md-4 am-avg-lg-6 am-thumbnails am-list am-list-striped mb0">-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_30_1.html" title="鲁迅"><i class="am-icon-book am-icon-fw"></i> 鲁迅</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_52_1.html" title="沈从文"><i class="am-icon-book am-icon-fw"></i> 沈从文</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_41_1.html" title="老舍"><i class="am-icon-book am-icon-fw"></i> 老舍</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_19_1.html" title="王朔"><i class="am-icon-book am-icon-fw"></i> 王朔</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_22_1.html" title="莫言"><i class="am-icon-book am-icon-fw"></i> 莫言</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_24_1.html" title="路遥"><i class="am-icon-book am-icon-fw"></i> 路遥</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_29_1.html" title="贾平凹"><i class="am-icon-book am-icon-fw"></i> 贾平凹</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_58_1.html" title="茅盾"><i class="am-icon-book am-icon-fw"></i> 茅盾</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_59_1.html" title="巴金"><i class="am-icon-book am-icon-fw"></i> 巴金</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_60_1.html" title="汪曾祺"><i class="am-icon-book am-icon-fw"></i> 汪曾祺</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_53_1.html" title="陈忠实"><i class="am-icon-book am-icon-fw"></i> 陈忠实</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_54_1.html" title="苏童"><i class="am-icon-book am-icon-fw"></i> 苏童</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_55_1.html" title="阿城"><i class="am-icon-book am-icon-fw"></i> 阿城</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_57_1.html" title="铁凝"><i class="am-icon-book am-icon-fw"></i> 铁凝</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_61_1.html" title="王安忆"><i class="am-icon-book am-icon-fw"></i> 王安忆</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_43_1.html" title="凌力"><i class="am-icon-book am-icon-fw"></i> 凌力</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_42_1.html" title="张恨水"><i class="am-icon-book am-icon-fw"></i> 张恨水</a></li>-->
<!--                            <li><a class="am-text-truncate" href="https://www.eeeaaa.cn/xiaoshuo/author_45_1.html" title="高阳"><i class="am-icon-book am-icon-fw"></i> 高阳</a></li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->