<?php $this->display('section/header.phtml');?>

<div class="category2top">
    <div class="am-g am-container userinfo">
        <div class="am-u-sm-12 am-u-md-12 am-u-lg-5 userinfo_left">
            <div class="am-g">
                <div class="am-u-md-12 am-u-lg-6 userface">
                    <img src="<?=\YC\Common::getUrl($this->author_info['pic'])?>" alt="<?=$this->author_info['author_name']?>">
                </div>
                <div class="am-u-md-12 am-u-lg-6 userin">
                    <h1><?=$this->author_info['author_name']?></h1>
                </div>
            </div>
        </div>
        <div class="am-u-sm-0 am-u-md-12 am-u-lg-7 am-show-lg-only userinfo_center">
            <?=$this->author_info['description']?>
        </div>
    </div>
</div>

<div class="am-g">
    <div class="am-u-sm-0 am-u-md-2 am-u-lg-3">&nbsp;</div>
    <div class="am-u-sm-12 am-u-md-8 am-u-lg-6">
        <div data-am-widget="list_news" class="am-list-news am-list-news-default ">
            <div class="am-list-news-bd">
                <ul class="am-list">
                    <?php foreach ($this->novel_list as $value){?>
                    <li class="am-g am-list-item-desced am-list-item-thumbed am-list-item-thumb-left" >
                        <div class="am-u-sm-5 am-list-thumb">
                            <a href="/xiaoshuo/charpter_<?=$value['id']?>_1.html" title="<?=$value['name']?>">
                                <img src="<?=\YC\Common::getUrl($this->author_info['pic'])?>" alt="<?=$value['name']?>"/>
                            </a>
                        </div>
                        <div class="am-u-sm-7 am-list-main">
                            <h2 class="am-list-item-hd fs16"><a href="/xiaoshuo/charpter_<?=$value['id']?>_1.html" title="<?=$value['name']?>"><?=$value['name']?></a></h2>
                            <div class="am-list-item-text"><?=mb_substr($value['content'],0,80,"UTF-8")?></div>
                        </div>
                    </li>
                    <?php }?>
                </ul>
            </div>
        </div>
    </div>
    <div class="am-u-sm-0 am-u-md-2 am-u-lg-3">&nbsp;</div>
</div>
<?php $this->display('section/footer.phtml');?>