<?php $this->display('section/header.phtml');?>

<div class="category2top">
    <div class="am-g am-container userinfo">
        <div class="am-u-sm-12 am-u-md-12 am-u-lg-5 userinfo_left">
            <div class="am-g">
                <div class="am-u-md-12 am-u-lg-6 userface">
                    <img src="<?=\YC\Common::getUrl($this->author_info['pic'])?>" alt="<?=$this->author_info['author_name']?>">
                </div>
                <div class="am-u-md-12 am-u-lg-6 userin">
                    <h1><?=$this->author_info['author_name']?></h1>
                </div>
            </div>
        </div>
        <div class="am-u-sm-0 am-u-md-12 am-u-lg-7 am-show-lg-only userinfo_center">
            <?=$this->author_info['description']?>
        </div>
    </div>
</div>

    <div class="am-list-news-bd am-container">
        <ul class="am-avg-sm-1 am-avg-md-3 am-avg-lg-5 am-thumbnails am-list">
<?php foreach ($this->novel_list as $value){?>
            <li class="am-g am-list-item-desced am-list-item-thumbed am-list-item-thumb-bottom-left">
                <h3 class="am-list-item-hd author_book_til">
                    <a href="<?=$this->web_url?>/xiaoshuo/chapter_<?=$value['id']?>_1.html" title="<?=$value['name']?>"><?=$value['name']?></a>
                </h3>
                <div class="am-u-sm-4 am-list-thumb author_book_left">
                    <a href="<?=$this->web_url?>/xiaoshuo/chapter_<?=$value['id']?>_1.html" title="<?=$value['name']?>">
                        <img class="am-thumbnail" src="<?=\YC\Common::getUrl($value['pic'])?>" alt="<?=$value['name']?>"/>
                    </a>
                </div>
                <div class="am-u-sm-8 am-list-main author_book_right">
                    <div class="am-list-item-text author_book_info"><?=$value['content']?></div>
                </div>
            </li>
<?php }?>
        </ul>
    </div>

<?php $this->display('section/footer.phtml');?>