<?php $this->display('section/header.phtml');?>
<div class="category2top">
    <div class="am-g am-container userinfo">
        <div class="am-u-sm-12 am-u-md-12 am-u-lg-5 userinfo_left">
            <div class="am-g">
                <div class="am-u-md-12 am-u-lg-6 userface">
                    <img src="<?=\YC\Common::getUrl($this->novel_info['pic'])?>" alt="著作名称">
                </div>
                <div class="am-u-md-12 am-u-lg-6 userin">
                    <h1><?=$this->novel_info['name']?></h1>
                </div>
            </div>
        </div>
        <div class="am-u-sm-0 am-u-md-12 am-u-lg-7 am-show-lg-only userinfo_center">
            <?=$this->novel_info['content']?>
        </div>
    </div>
</div>

<div class="am-g">
    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
        <ul class="am-avg-sm-1 am-avg-md-3 am-avg-lg-4 am-thumbnails am-list am-list-striped">
            <?php foreach ($this->list as $value){?>
            <li><a class="am-text-truncate" href="/xiaoshuo/detail_<?=$value['id']?>.html" title="<?=$value['title']?>"><i class="am-icon-book am-icon-fw"></i> <?=$value['title']?></a></li>
            <?php }?>
        </ul>
    </div>
</div>
<?php $this->display('section/footer.phtml');?>