<?php $this->display('section/header.phtml');?>

<div class="am-g am-container">
    <div class="am-u-sm-12 am-u-md-12 am-u-lg-8">
        <ol class="am-breadcrumb breadcrumb">
            <li><a href="<?=$this->web_url?>" title="文学星空" class="am-icon-home">首页</a></li>
            <li>
                <a href="<?=$this->web_url?>/xiaoshuo/<?=NovelModel::$_novel_class_pinxie[$this->novel['novel_class_id']]?>_<?=$this->novel['novel_class_id']?>.html" title="<?=NovelModel::$_novel_class_type[$this->novel['novel_class_id']]?>小说">
                    <strong class="fn"><?=NovelModel::$_novel_class_type[$this->novel['novel_class_id']]?>小说</strong>
                </a>
            </li>
            <li>
                <a href="<?=$this->web_url?>/xiaoshuo/author_<?=$this->novel['author_id']?>_1.html" title="<?=$this->novel['author_name']?>"><strong class="fn">#<?=$this->novel['author_name']?>#</strong></a>
                <a href="<?=$this->web_url?>/xiaoshuo/chapter_<?=$this->novel['id']?>_1.html" title="<?=$this->novel['name']?>"><strong class="fn">#<?=$this->novel['name']?>#</strong></a>
            </li>
        </ol>
        <div>
            <h1><?=$this->chapter['title']?></h1>
        </div>
        <div class="contents">
            <?php
                 $content = $this->chapter['content'];
                 $start_div_num = substr_count($this->chapter['content'],"<div");
                 $end_div_num = substr_count($this->chapter['content'],"</div");
                 if($start_div_num > $end_div_num){
                     $num = $start_div_num - $end_div_num;
                     for($i=0;$i<$num;$i++){
                         $content = $content."</div>";
                     }
                 }
                if($start_div_num < $end_div_num){
                    $num = $end_div_num - $start_div_num;
                    for($i=0;$i<$num;$i++){
                        $content = "<div>".$content;
                     }
                }


                 $pNum = substr_count($content,"</p>");
                 $brNum = substr_count($content,"<br");
                 $location = 0;
                 if($pNum > $brNum){
                     $lNum = ceil($pNum/2);
                     $str = "</p>";
                 }else if ($brNum > 0){
                     $lNum = ceil($brNum/2);
                     $str = "<br";
                 }

            $i = $l = 0;
            while ($location = strpos($content,$str,$l)){
                $i++;
                $l = $location + strlen($str);
                if($i == $lNum){
                    break;
                }
            }

                if($location > 0){

                    $novelContent = substr($content,0,$location)."<strong><a id='eeeaaa' href='".$this->web_url."' title='文学星空'>文学星空</a ></strong>".substr($content,$location);
                }else{
                    $novelContent = $content."<strong><a id='eeeaaa' href='".$this->web_url."' title='文学星空'>文学星空</a ></strong>";
                }

                echo $novelContent;

            ?>
        </div>
        <ul data-am-widget="pagination" class="am-pagination am-pagination-default">
            <?php if($this->chapter['pre']){?>
            <li class="am-pagination-prev ">
                <a href="<?=$this->web_url?>/xiaoshuo/detail_<?=$this->chapter['pre']?>.html" class="">上一章</a>
            </li>
            <?php }?>
            <li class="">
                <a href="<?=$this->web_url?>/xiaoshuo/chapter_<?=$this->novel['id']?>_1.html" class="">回目录</a>
            </li>
            <?php if($this->chapter['next']){?>
            <li class="am-pagination-next ">
                <a href="<?=$this->web_url?>/xiaoshuo/detail_<?=$this->chapter['next']?>.html" class="">下一章</a>
            </li>
            <?php }?>
        </ul>
    </div>
    <div class="am-u-sm-0 am-u-md-0 am-u-lg-4">
        <div data-am-widget="titlebar" class="am-titlebar am-titlebar-default">
            <h2 class="am-titlebar-title ">
                <?=$this->novel['author_name']?>作品
            </h2>
            <nav class="am-titlebar-nav">
                <a href="<?=$this->web_url?>/xiaoshuo/author_<?=$this->novel['author_id']?>_1.html" title="<?=$this->novel['name']?>">more &raquo;</a>
            </nav>
        </div>
        <div data-am-widget="list_news" class="am-list-news am-list-news-default right-bg">
            <ul class="am-list">
                <?php foreach ($this->author_novel as $value){
                        if($value['id'] == $this->novel['id'])continue;
                    ?>
                <li class="am-g am-list-item-desced am-list-item-thumbed am-list-item-thumb-left">
                    <div class="am-u-sm-4 am-list-thumb">
                        <a href="<?=$this->web_url?>/xiaoshuo/chapter_<?=$value['id']?>_1.html" title="<?=$value['name']?>">
                            <img src="<?=\YC\Common::getUrl($value['pic'])?>" alt="<?=$value['name']?>" class="face"/>
                        </a>
                    </div>
                    <div class=" am-u-sm-8 am-list-main">
                        <h3 class="am-list-item-hd"><a href="<?=$this->web_url?>/xiaoshuo/chapter_<?=$value['id']?>_1.html" title="<?=$value['name']?>"><?=$value['name']?></a></h3>
                        <div class="am-list-item-text"><?=$value['content']?></div>
                    </div>
                </li>
                    <hr data-am-widget="divider" style="" class="am-divider am-divider-default" />
                <?php }?>
            </ul>
        </div>

        <div data-am-widget="titlebar" class="am-titlebar am-titlebar-default">
            <h2 class="am-titlebar-title ">
                相关作品
            </h2>
            <nav class="am-titlebar-nav">
                <a href="<?=$this->web_url?>/xiaoshuo/<?=NovelModel::$_novel_class_pinxie[$this->novel['novel_class_id']]?>_1.html">more &raquo;</a>
            </nav>
        </div>

        <div data-am-widget="list_news" class="am-list-news am-list-news-default right-bg">
            <ul class="am-list"  >
                <?php foreach ($this->relate_novel as $value) {
                    if($value['id'] == $this->novel['id'])continue;
                    ?>
                <li class="am-g am-list-item-desced am-list-item-thumbed am-list-item-thumb-left">
                    <div class="am-u-sm-4 am-list-thumb">
                        <a href="<?=$this->web_url?>/xiaoshuo/chapter_<?=$value['id']?>_1.html" title="<?=$value['author_name']?>/<?=$value['name']?>">
                            <img src="<?=\YC\Common::getUrl($value['pic'])?>" class="face" alt="<?=$value['author_name']?>/<?=$value['name']?>"/>
                        </a>
                    </div>
                    <div class=" am-u-sm-8 am-list-main">
                        <h3 class="am-list-item-hd" title="<?=$value['author_name']?>/<?=$value['name']?>">
                            <a href="<?=$this->web_url?>/xiaoshuo/chapter_<?=$value['id']?>_1.html"><?=$value['author_name']?>/<?=$value['name']?></a>
                        </h3>

                        <div class="am-list-item-text"><?=$value['content']?></div>
                    </div>
                </li>
                <hr data-am-widget="divider" style="" class="am-divider am-divider-default" />
                <?php } ?>

            </ul>
        </div>

    </div>
</div>
<?php $this->display('section/footer.phtml');?>