<?php $this->display('section/header.phtml');?>

<div class="am-g am-container">
    <div class="am-u-sm-12 am-u-md-12 am-u-lg-8">
        <ol class="am-breadcrumb breadcrumb">
            <li><a href="<?=$this->web_url?>" title="文学星空" class="am-icon-home">首页</a></li>
            <li>
                <a href="<?=$this->web_url?>/gudian/<?=NovelModel::$_novel_class_pinxie[$this->novel['novel_class_id']]?>_<?=$this->novel['novel_class_id']?>.html" title="<?=NovelModel::$_novel_class_type[$this->novel['novel_class_id']]?>小说">
                    <strong class="fn"><?=NovelModel::$_novel_class_type[$this->novel['novel_class_id']]?>小说</strong>
                </a>
            </li>
            <li>
                <a href="<?=$this->web_url?>/gudian/author_<?=$this->novel['author_id']?>_1.html" title="<?=$this->novel['author_name']?>"><strong class="fn">#<?=$this->novel['author_name']?>#</strong></a>
                <a href="<?=$this->web_url?>/gudian/chapter_<?=$this->novel['id']?>_1.html" title="<?=$this->novel['name']?>"><strong class="fn">#<?=$this->novel['name']?>#</strong></a>
            </li>
        </ol>
        <div class="clearfix">
            <h1 class="l"><?=$this->chapter['title']?></h1>
            <div class="am-dropdown am-hide-sm-only l btn-ewm" data-am-dropdown>
                <button class="am-btn am-btn-xs am-radius am-btn-success am-dropdown-toggle">点击扫描二维码 <span class="am-icon-qrcode" style="font-size: 16px;vertical-align: middle"></span></button>
                <div class="am-dropdown-content">
                    <h3 style="text-align: center">手机扫描下方二维码，移动端阅读</h3>
                    <div id="doc-qrcode"></div>
                </div>
            </div>
            <div class="bdsharebuttonbox am-show-lg-only r">
                <a href=" " class="bds_more" data-cmd="more"></a >
                <a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a >
                <a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a >
            </div>
        </div>
        <div class="contents">
            <?php
                 $content = $this->chapter['content'];
                 $start_div_num = substr_count($this->chapter['content'],"<div");
                 $end_div_num = substr_count($this->chapter['content'],"</div");
                 if($start_div_num > $end_div_num){
                     $num = $start_div_num - $end_div_num;
                     for($i=0;$i<$num;$i++){
                         $content = $content."</div>";
                     }
                 }
                if($start_div_num < $end_div_num){
                    $num = $end_div_num - $start_div_num;
                    for($i=0;$i<$num;$i++){
                        $content = "<div>".$content;
                     }
                }


                 $pNum = substr_count($content,"</p>");
                 $brNum = substr_count($content,"<br");
                 $location = 0;
                 if($pNum > $brNum){
                     $lNum = ceil($pNum/2);
                     $str = "</p>";
                 }else if ($brNum > 0){
                     $lNum = ceil($brNum/2);
                     $str = "<br";
                 }

            $i = $l = 0;
            while ($location = strpos($content,$str,$l)){
                $i++;
                $l = $location + strlen($str);
                if($i == $lNum){
                    break;
                }
            }

                if($location > 0){

                    $novelContent = substr($content,0,$location)."<strong><a id='eeeaaa' href='".$this->web_url."' title='文学星空'>文学星空</a ></strong>".substr($content,$location);
                }else{
                    $novelContent = $content."<strong><a id='eeeaaa' href='".$this->web_url."' title='文学星空'>文学星空</a ></strong>";
                }

                echo $novelContent;

            ?>
        </div>
        <ul data-am-widget="pagination" class="am-pagination am-pagination-default">
            <?php if($this->chapter['pre']){?>
            <li class="am-pagination-prev ">
                <a href="<?=$this->web_url?>/gudian/detail_<?=$this->chapter['pre']?>.html" class="">上一章</a>
            </li>
            <?php }?>
            <li class="">
                <a href="<?=$this->web_url?>/gudian/chapter_<?=$this->novel['id']?>_1.html" class="">回目录</a>
            </li>
            <?php if($this->chapter['next']){?>
            <li class="am-pagination-next ">
                <a href="<?=$this->web_url?>/gudian/detail_<?=$this->chapter['next']?>.html" class="">下一章</a>
            </li>
            <?php }?>
        </ul>

        <!--detail left pc-->
        <div class="clearfix" style="background: #f5f5f5">
            <div class="l">
                <div class="_7wlyoumvy8c"></div>
                <script type="text/javascript">
                    if(!(navigator.userAgent.match(/(phone|pad|pod|iPhone|iPod|ios|iPad|Android|Mobile|BlackBerry|IEMobile|MQQBrowser|JUC|Fennec|wOSBrowser|BrowserNG|WebOS|Symbian|Windows Phone)/i))) {
                        (window.slotbydup = window.slotbydup || []).push({
                            id: "u6035041",
                            container: "_7wlyoumvy8c",
                            async: true
                        });
                    }
                </script>
            </div>
            <div class="l">
                <div class="_0uoc129zh6x"></div>
                <script type="text/javascript">
                    if(!(navigator.userAgent.match(/(phone|pad|pod|iPhone|iPod|ios|iPad|Android|Mobile|BlackBerry|IEMobile|MQQBrowser|JUC|Fennec|wOSBrowser|BrowserNG|WebOS|Symbian|Windows Phone)/i))) {
                        (window.slotbydup = window.slotbydup || []).push({
                            id: "u6035050",
                            container: "_0uoc129zh6x",
                            async: true
                        });
                    }
                </script>
            </div>
        </div>

        <!--detail left wap-->
        <div>
            <div class="_nkw7kxa60r"></div>
            <script type="text/javascript">
                if((navigator.userAgent.match(/(phone|pad|pod|iPhone|iPod|ios|iPad|Android|Mobile|BlackBerry|IEMobile|MQQBrowser|JUC|Fennec|wOSBrowser|BrowserNG|WebOS|Symbian|Windows Phone)/i))) {
                    (window.slotbydup = window.slotbydup || []).push({
                        id: "u6035051",
                        container: "_nkw7kxa60r",
                        async: true
                    });
                }
            </script>
        </div>
    </div>
    <div class="am-u-sm-0 am-u-md-0 am-u-lg-4">
        <!--<div data-am-widget="titlebar" class="am-titlebar am-titlebar-default">
            <h2 class="am-titlebar-title ">
                扫描二维码关注微信公众号『星阅』
            </h2>
        </div>
        <div data-am-widget="list_news" class="am-list-news am-list-news-default right-bg">
            <div class="tc"><img style="width: 258px;height: 258px" src="/images/qrcode_258.jpg"/></div>
        </div>-->

        <!--detail right pc-->
        <div>
            <div class="_pvoj0j3bq"></div>
            <script type="text/javascript">
                if(!(navigator.userAgent.match(/(phone|pad|pod|iPhone|iPod|ios|iPad|Android|Mobile|BlackBerry|IEMobile|MQQBrowser|JUC|Fennec|wOSBrowser|BrowserNG|WebOS|Symbian|Windows Phone)/i))) {
                    (window.slotbydup = window.slotbydup || []).push({
                        id: "u6035153",
                        container: "_pvoj0j3bq",
                        async: true
                    });
                }
            </script>
        </div>

        <div data-am-widget="titlebar" class="am-titlebar am-titlebar-default">
            <h2 class="am-titlebar-title ">
                <?=$this->novel['author_name']?>作品
            </h2>
            <nav class="am-titlebar-nav">
                <a href="<?=$this->web_url?>/gudian/author_<?=$this->novel['author_id']?>_1.html" title="<?=$this->novel['author_name']?>作品">more &raquo;</a>
            </nav>
        </div>
        <div data-am-widget="list_news" class="am-list-news am-list-news-default right-bg">
            <ul class="am-list">
                <?php foreach ($this->author_novel as $value){
                        //if($value['id'] == $this->novel['id'])continue;
                    ?>
                <li class="am-g am-list-item-desced am-list-item-thumbed am-list-item-thumb-left">
                    <div class="am-u-sm-4 am-list-thumb">
                        <a href="<?=$this->web_url?>/gudian/chapter_<?=$value['id']?>_1.html" title="<?=$this->novel['author_name']?>作品:<?=$value['name']?>">
                            <img src="<?=\YC\Common::getUrl($value['pic'])?>" alt="<?=$this->novel['author_name']?>作品:<?=$value['name']?>" class="face"/>
                        </a>
                    </div>
                    <div class=" am-u-sm-8 am-list-main">
                        <h3 class="am-list-item-hd"><a href="<?=$this->web_url?>/gudian/chapter_<?=$value['id']?>_1.html" title="<?=$this->novel['author_name']?>作品:<?=$value['name']?>"><?=$value['name']?></a></h3>
                        <div class="am-list-item-text"><?=$value['content']?></div>
                    </div>
                </li>
                    <hr data-am-widget="divider" style="" class="am-divider am-divider-default" />
                <?php }?>
            </ul>
        </div>

        <div data-am-widget="titlebar" class="am-titlebar am-titlebar-default">
            <h2 class="am-titlebar-title ">
                相关作品
            </h2>
            <nav class="am-titlebar-nav">
                <a href="<?=$this->web_url?>/gudian/<?=NovelModel::$_novel_class_pinxie[$this->novel['novel_class_id']]?>_1.html">more &raquo;</a>
            </nav>
        </div>

        <div data-am-widget="list_news" class="am-list-news am-list-news-default right-bg">
            <ul class="am-list"  >
                <?php foreach ($this->relate_novel as $value) {
                    if($value['id'] == $this->novel['id'])continue;
                    ?>
                <li class="am-g am-list-item-desced am-list-item-thumbed am-list-item-thumb-left">
                    <div class="am-u-sm-4 am-list-thumb">
                        <a href="<?=$this->web_url?>/gudian/chapter_<?=$value['id']?>_1.html" title="<?=$value['author_name']?>/<?=$value['name']?>">
                            <img src="<?=\YC\Common::getUrl($value['pic'])?>" class="face" alt="<?=$value['author_name']?>/<?=$value['name']?>"/>
                        </a>
                    </div>
                    <div class=" am-u-sm-8 am-list-main">
                        <h3 class="am-list-item-hd" title="<?=$value['author_name']?>/<?=$value['name']?>">
                            <a href="<?=$this->web_url?>/gudian/chapter_<?=$value['id']?>_1.html"><?=$value['author_name']?>/<?=$value['name']?></a>
                        </h3>

                        <div class="am-list-item-text"><?=$value['content']?></div>
                    </div>
                </li>
                <hr data-am-widget="divider" style="" class="am-divider am-divider-default" />
                <?php } ?>

            </ul>
        </div>

    </div>
</div>

<script>
    window._bd_share_config = {
        "common": {
            "bdSnsKey": {},
            "bdText": "爱好文学的你，是否在静静夜里，仰望星空？期待一个不凡的夜……",
            "bdMini": "2",
            "bdMiniList": false,
            "bdPic": "https://www.eeeaaa.cn/images/logo_eeeaaa_web.png",
            "bdStyle": "0",
            "bdSize": "24"
        }, "share": {}
    };
    with (document)0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = '/static/api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];
</script>

<?php $this->display('section/footer.phtml');?>