<?php $this->display('section/header.phtml');?>

<h1 class="star am-container mcenter"><span><img src="/images/star.png" alt="<?=NovelModel::$_novel_class_type[$class_type_id]?>小说"><?=NovelModel::$_novel_class_type[$class_type_id]?>小说</span></h1>
<div id="cattlist" class="am-container">
    <ul class="am-avg-sm-1 am-avg-md-3 am-avg-lg-4">
        <?php foreach ($this->novel_list as $value){?>
        <li>
            <div class="cattlist_0">
                <div class="cattlist_1">
                    <div class="am-g">
                        <div class="am-u-sm-4 am-u-md-5 am-u-lg-5 am-vertical-align">
                            <div class="am-vertical-align-middle">
                                <img src="<?=\YC\Common::getUrl($value['pic'])?>" alt="<?=NovelModel::$_novel_class_type[$class_type_id]?>小说作者：<?=$value['name']?>">
                            </div>
                        </div>
                        <div class="am-u-sm-8 am-u-md-7 am-u-lg-7">
                            <h2><?=$value['name']?></h2>
                            <h3><?=NovelModel::$_novel_class_type[$class_type_id]?>小说作者</h3>
                        </div>
                    </div>
                </div>
                <div class="cattlist_2">
                    <p><?=$value['name']?>简介：<?=$value['content']?></p>
                </div>
                <div class="cattlist_3">
                    <a class="am-btn am-btn-warning" title="<?=NovelModel::$_novel_class_type[$class_type_id]?>小说作者：<?=$value['name']?>" href="<?=$this->web_url?>/xiaoshuo/chapter_<?=$value['id']?>_1.html">开始阅读</a>
                </div>
            </div>
        </li>
    <?php }?>
    </ul>
</div>

<?php $this->display('section/footer.phtml');?>